# Open file in RStudio and choose Source with Echo, or
# Type 'source("demo/FD_PlotTerminalValue.R",echo=TRUE)', or
# Type 'demo(FD_PlotTerminalValue)'
# R6 object
FD <- FiniteDifference$new()
# by name, no labels
FD$set_plot_info(labels=FALSE)
V_Info <- FD$set_V_info("Linear")
FD$PlotTerminalValue()
V_Info <- FD$set_V_info("Degenerate")
FD$PlotTerminalValue()
V_Info <- FD$set_V_info("Kinked")
FD$PlotTerminalValue()
V_Info <- FD$set_V_info("Stepped")
FD$PlotTerminalValue()
V_Info <- FD$set_V_info("Mitscherlich")
FD$PlotTerminalValue()
V_Info <- FD$set_V_info("Gompertz")
FD$PlotTerminalValue()
V_Info <- FD$set_V_info("Logistic")
FD$PlotTerminalValue()
V_Info <- FD$set_V_info("Transcendental")
FD$PlotTerminalValue()
V_Info <- FD$set_V_info("Yield Index")
FD$PlotTerminalValue()
# by number with labels
FD$set_plot_info(labels=TRUE)
V_Info <- FD$set_V_info(1)
FD$PlotTerminalValue()
V_Info <- FD$set_V_info(2)
FD$PlotTerminalValue()
V_Info <- FD$set_V_info(3)
FD$PlotTerminalValue()
V_Info <- FD$set_V_info(4)
FD$PlotTerminalValue()
V_Info <- FD$set_V_info(5)
FD$PlotTerminalValue()
V_Info <- FD$set_V_info(6)
FD$PlotTerminalValue()
V_Info <- FD$set_V_info(7)
FD$PlotTerminalValue()
V_Info <- FD$set_V_info(8)
FD$PlotTerminalValue()
V_Info <- FD$set_V_info(9)
FD$PlotTerminalValue()
# with custom title
FD$PlotTerminalValue(title="My Title")
