// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RcppOUPADrift
NumericVector RcppOUPADrift(NumericVector z, double rho, double mu);
RcppExport SEXP _GregsOUPR6_RcppOUPADrift(SEXP zSEXP, SEXP rhoSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPADrift(z, rho, mu));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPADiffusion
NumericVector RcppOUPADiffusion(NumericVector z, double sigma);
RcppExport SEXP _GregsOUPR6_RcppOUPADiffusion(SEXP zSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPADiffusion(z, sigma));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPAMean
NumericVector RcppOUPAMean(NumericVector t, double s, double x, double rho, double mu, double eps);
RcppExport SEXP _GregsOUPR6_RcppOUPAMean(SEXP tSEXP, SEXP sSEXP, SEXP xSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPAMean(t, s, x, rho, mu, eps));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPAVariance
NumericVector RcppOUPAVariance(NumericVector t, double s, double rho, double sigma, double eps);
RcppExport SEXP _GregsOUPR6_RcppOUPAVariance(SEXP tSEXP, SEXP sSEXP, SEXP rhoSEXP, SEXP sigmaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPAVariance(t, s, rho, sigma, eps));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPADensity
NumericMatrix RcppOUPADensity(NumericVector t, NumericVector y, double s, double x, double rho, double mu, double sigma);
RcppExport SEXP _GregsOUPR6_RcppOUPADensity(SEXP tSEXP, SEXP ySEXP, SEXP sSEXP, SEXP xSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPADensity(t, y, s, x, rho, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPAProbability
NumericMatrix RcppOUPAProbability(NumericVector t, NumericVector y, double s, double x, double rho, double mu, double sigma, double psi);
RcppExport SEXP _GregsOUPR6_RcppOUPAProbability(SEXP tSEXP, SEXP ySEXP, SEXP sSEXP, SEXP xSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPAProbability(t, y, s, x, rho, mu, sigma, psi));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPADoubleIntegral
NumericMatrix RcppOUPADoubleIntegral(NumericVector t, NumericVector y, double s, double x, double rho, double mu, double sigma, double psi);
RcppExport SEXP _GregsOUPR6_RcppOUPADoubleIntegral(SEXP tSEXP, SEXP ySEXP, SEXP sSEXP, SEXP xSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPADoubleIntegral(t, y, s, x, rho, mu, sigma, psi));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPAOption
NumericMatrix RcppOUPAOption(NumericVector s, NumericVector x, double t, double y, double rho, double mu, double sigma, double r, double phi, double b, double c);
RcppExport SEXP _GregsOUPR6_RcppOUPAOption(SEXP sSEXP, SEXP xSEXP, SEXP tSEXP, SEXP ySEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP rSEXP, SEXP phiSEXP, SEXP bSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPAOption(s, x, t, y, rho, mu, sigma, r, phi, b, c));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPAOptionEnvelope
NumericMatrix RcppOUPAOptionEnvelope(NumericVector s, NumericVector x, double t, double y, double rho, double mu, double sigma, double r, double phi, double b, double c);
RcppExport SEXP _GregsOUPR6_RcppOUPAOptionEnvelope(SEXP sSEXP, SEXP xSEXP, SEXP tSEXP, SEXP ySEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP rSEXP, SEXP phiSEXP, SEXP bSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPAOptionEnvelope(s, x, t, y, rho, mu, sigma, r, phi, b, c));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPAdOOdsZero
NumericMatrix RcppOUPAdOOdsZero(NumericVector s, NumericVector x, double t, double y, double rho, double mu, double sigma, double r, double phi, double b, double c);
RcppExport SEXP _GregsOUPR6_RcppOUPAdOOdsZero(SEXP sSEXP, SEXP xSEXP, SEXP tSEXP, SEXP ySEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP rSEXP, SEXP phiSEXP, SEXP bSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPAdOOdsZero(s, x, t, y, rho, mu, sigma, r, phi, b, c));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPADecisionThreshold
NumericVector RcppOUPADecisionThreshold(double y, double rho, double mu, double sigma, double r, double phi, double b, double c);
RcppExport SEXP _GregsOUPR6_RcppOUPADecisionThreshold(SEXP ySEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP rSEXP, SEXP phiSEXP, SEXP bSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPADecisionThreshold(y, rho, mu, sigma, r, phi, b, c));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPAObligation
NumericMatrix RcppOUPAObligation(NumericVector s, NumericVector x, double t, double y, double rho, double mu, double r, double phi, double b, double c);
RcppExport SEXP _GregsOUPR6_RcppOUPAObligation(SEXP sSEXP, SEXP xSEXP, SEXP tSEXP, SEXP ySEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP rSEXP, SEXP phiSEXP, SEXP bSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPAObligation(s, x, t, y, rho, mu, r, phi, b, c));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPAPassageTimeModeMedianMean
NumericMatrix RcppOUPAPassageTimeModeMedianMean(double k, double s, double x, double omega, double rho, double mu, double sigma, Nullable<NumericVector> z);
RcppExport SEXP _GregsOUPR6_RcppOUPAPassageTimeModeMedianMean(SEXP kSEXP, SEXP sSEXP, SEXP xSEXP, SEXP omegaSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPAPassageTimeModeMedianMean(k, s, x, omega, rho, mu, sigma, z));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPAPassageTimePercentiles
NumericMatrix RcppOUPAPassageTimePercentiles(double k, double s, double x, double omega, double Ppct, double rho, double mu, double sigma, Nullable<NumericVector> z);
RcppExport SEXP _GregsOUPR6_RcppOUPAPassageTimePercentiles(SEXP kSEXP, SEXP sSEXP, SEXP xSEXP, SEXP omegaSEXP, SEXP PpctSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type Ppct(PpctSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPAPassageTimePercentiles(k, s, x, omega, Ppct, rho, mu, sigma, z));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPAPassageTimeDensity
NumericMatrix RcppOUPAPassageTimeDensity(NumericVector t, double k, double s, double x, double omega, double rho, double mu, double sigma, Nullable<NumericVector> z);
RcppExport SEXP _GregsOUPR6_RcppOUPAPassageTimeDensity(SEXP tSEXP, SEXP kSEXP, SEXP sSEXP, SEXP xSEXP, SEXP omegaSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPAPassageTimeDensity(t, k, s, x, omega, rho, mu, sigma, z));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPAPassageTimeProbability
NumericMatrix RcppOUPAPassageTimeProbability(NumericVector t, double k, double s, double x, double omega, double rho, double mu, double sigma, Nullable<NumericVector> z);
RcppExport SEXP _GregsOUPR6_RcppOUPAPassageTimeProbability(SEXP tSEXP, SEXP kSEXP, SEXP sSEXP, SEXP xSEXP, SEXP omegaSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPAPassageTimeProbability(t, k, s, x, omega, rho, mu, sigma, z));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDDrift
NumericVector RcppOUPFDDrift(NumericVector x, double rho, double mu);
RcppExport SEXP _GregsOUPR6_RcppOUPFDDrift(SEXP xSEXP, SEXP rhoSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDDrift(x, rho, mu));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDDiffusion
NumericVector RcppOUPFDDiffusion(NumericVector x, double sigma);
RcppExport SEXP _GregsOUPR6_RcppOUPFDDiffusion(SEXP xSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDDiffusion(x, sigma));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDTerminalValue_Linear
NumericVector RcppOUPFDTerminalValue_Linear(NumericVector x, double xo, double vs);
RcppExport SEXP _GregsOUPR6_RcppOUPFDTerminalValue_Linear(SEXP xSEXP, SEXP xoSEXP, SEXP vsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xo(xoSEXP);
    Rcpp::traits::input_parameter< double >::type vs(vsSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDTerminalValue_Linear(x, xo, vs));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDTerminalValue_Degenerate
NumericVector RcppOUPFDTerminalValue_Degenerate(NumericVector x, double xo, double Vmax, double Vmin);
RcppExport SEXP _GregsOUPR6_RcppOUPFDTerminalValue_Degenerate(SEXP xSEXP, SEXP xoSEXP, SEXP VmaxSEXP, SEXP VminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xo(xoSEXP);
    Rcpp::traits::input_parameter< double >::type Vmax(VmaxSEXP);
    Rcpp::traits::input_parameter< double >::type Vmin(VminSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDTerminalValue_Degenerate(x, xo, Vmax, Vmin));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDTerminalValue_Stepped
NumericVector RcppOUPFDTerminalValue_Stepped(NumericVector x, double xo, double vs, double Vmax, double Vmin);
RcppExport SEXP _GregsOUPR6_RcppOUPFDTerminalValue_Stepped(SEXP xSEXP, SEXP xoSEXP, SEXP vsSEXP, SEXP VmaxSEXP, SEXP VminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xo(xoSEXP);
    Rcpp::traits::input_parameter< double >::type vs(vsSEXP);
    Rcpp::traits::input_parameter< double >::type Vmax(VmaxSEXP);
    Rcpp::traits::input_parameter< double >::type Vmin(VminSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDTerminalValue_Stepped(x, xo, vs, Vmax, Vmin));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDTerminalValue_Kinked
NumericVector RcppOUPFDTerminalValue_Kinked(NumericVector x, double xo, double vs, double Vmax, double Vmin);
RcppExport SEXP _GregsOUPR6_RcppOUPFDTerminalValue_Kinked(SEXP xSEXP, SEXP xoSEXP, SEXP vsSEXP, SEXP VmaxSEXP, SEXP VminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xo(xoSEXP);
    Rcpp::traits::input_parameter< double >::type vs(vsSEXP);
    Rcpp::traits::input_parameter< double >::type Vmax(VmaxSEXP);
    Rcpp::traits::input_parameter< double >::type Vmin(VminSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDTerminalValue_Kinked(x, xo, vs, Vmax, Vmin));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDTerminalValue_Butterfly
NumericVector RcppOUPFDTerminalValue_Butterfly(NumericVector x, double xo, double xm, double vs, double Vmax, double Vmin);
RcppExport SEXP _GregsOUPR6_RcppOUPFDTerminalValue_Butterfly(SEXP xSEXP, SEXP xoSEXP, SEXP xmSEXP, SEXP vsSEXP, SEXP VmaxSEXP, SEXP VminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xo(xoSEXP);
    Rcpp::traits::input_parameter< double >::type xm(xmSEXP);
    Rcpp::traits::input_parameter< double >::type vs(vsSEXP);
    Rcpp::traits::input_parameter< double >::type Vmax(VmaxSEXP);
    Rcpp::traits::input_parameter< double >::type Vmin(VminSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDTerminalValue_Butterfly(x, xo, xm, vs, Vmax, Vmin));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDTerminalValue_Mitscherlich
NumericVector RcppOUPFDTerminalValue_Mitscherlich(NumericVector x, double xo, double vr, double Vmax, double Vmin);
RcppExport SEXP _GregsOUPR6_RcppOUPFDTerminalValue_Mitscherlich(SEXP xSEXP, SEXP xoSEXP, SEXP vrSEXP, SEXP VmaxSEXP, SEXP VminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xo(xoSEXP);
    Rcpp::traits::input_parameter< double >::type vr(vrSEXP);
    Rcpp::traits::input_parameter< double >::type Vmax(VmaxSEXP);
    Rcpp::traits::input_parameter< double >::type Vmin(VminSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDTerminalValue_Mitscherlich(x, xo, vr, Vmax, Vmin));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDTerminalValue_Gompertz
NumericVector RcppOUPFDTerminalValue_Gompertz(NumericVector x, double xi, double vr, double Vmax, double Vmin);
RcppExport SEXP _GregsOUPR6_RcppOUPFDTerminalValue_Gompertz(SEXP xSEXP, SEXP xiSEXP, SEXP vrSEXP, SEXP VmaxSEXP, SEXP VminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type vr(vrSEXP);
    Rcpp::traits::input_parameter< double >::type Vmax(VmaxSEXP);
    Rcpp::traits::input_parameter< double >::type Vmin(VminSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDTerminalValue_Gompertz(x, xi, vr, Vmax, Vmin));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDTerminalValue_Logistic
NumericVector RcppOUPFDTerminalValue_Logistic(NumericVector x, double xi, double vr, double Vmax, double Vmin);
RcppExport SEXP _GregsOUPR6_RcppOUPFDTerminalValue_Logistic(SEXP xSEXP, SEXP xiSEXP, SEXP vrSEXP, SEXP VmaxSEXP, SEXP VminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type vr(vrSEXP);
    Rcpp::traits::input_parameter< double >::type Vmax(VmaxSEXP);
    Rcpp::traits::input_parameter< double >::type Vmin(VminSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDTerminalValue_Logistic(x, xi, vr, Vmax, Vmin));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDTerminalValue_Transcendental
NumericVector RcppOUPFDTerminalValue_Transcendental(NumericVector x, double xo, double xi, double xm, double Vmax, double Vmin);
RcppExport SEXP _GregsOUPR6_RcppOUPFDTerminalValue_Transcendental(SEXP xSEXP, SEXP xoSEXP, SEXP xiSEXP, SEXP xmSEXP, SEXP VmaxSEXP, SEXP VminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xo(xoSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type xm(xmSEXP);
    Rcpp::traits::input_parameter< double >::type Vmax(VmaxSEXP);
    Rcpp::traits::input_parameter< double >::type Vmin(VminSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDTerminalValue_Transcendental(x, xo, xi, xm, Vmax, Vmin));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDTerminalValue_YieldIndex
NumericVector RcppOUPFDTerminalValue_YieldIndex(NumericVector x, double xo, double xi, double xm, double Vmax, double Vmin);
RcppExport SEXP _GregsOUPR6_RcppOUPFDTerminalValue_YieldIndex(SEXP xSEXP, SEXP xoSEXP, SEXP xiSEXP, SEXP xmSEXP, SEXP VmaxSEXP, SEXP VminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type xo(xoSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type xm(xmSEXP);
    Rcpp::traits::input_parameter< double >::type Vmax(VmaxSEXP);
    Rcpp::traits::input_parameter< double >::type Vmin(VminSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDTerminalValue_YieldIndex(x, xo, xi, xm, Vmax, Vmin));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDOption
NumericMatrix RcppOUPFDOption(NumericVector s, NumericVector x, NumericVector V, double r, double theta, int skip, double rho, double mu, double sigma);
RcppExport SEXP _GregsOUPR6_RcppOUPFDOption(SEXP sSEXP, SEXP xSEXP, SEXP VSEXP, SEXP rSEXP, SEXP thetaSEXP, SEXP skipSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDOption(s, x, V, r, theta, skip, rho, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDOptionEnvelope
NumericVector RcppOUPFDOptionEnvelope(NumericVector s, NumericVector x, NumericVector V, double r, double theta, int skip, double rho, double mu, double sigma);
RcppExport SEXP _GregsOUPR6_RcppOUPFDOptionEnvelope(SEXP sSEXP, SEXP xSEXP, SEXP VSEXP, SEXP rSEXP, SEXP thetaSEXP, SEXP skipSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDOptionEnvelope(s, x, V, r, theta, skip, rho, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPFDDecisionThreshold
NumericVector RcppOUPFDDecisionThreshold(NumericVector x, NumericVector V, NumericVector OOenv, double phi);
RcppExport SEXP _GregsOUPR6_RcppOUPFDDecisionThreshold(SEXP xSEXP, SEXP VSEXP, SEXP OOenvSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type OOenv(OOenvSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPFDDecisionThreshold(x, V, OOenv, phi));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMLLogLikelihood
NumericVector RcppOUPMLLogLikelihood(NumericVector tau, NumericVector z, double rho, double mu, double sigma);
RcppExport SEXP _GregsOUPR6_RcppOUPMLLogLikelihood(SEXP tauSEXP, SEXP zSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMLLogLikelihood(tau, z, rho, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMLNMStart
NumericMatrix RcppOUPMLNMStart(NumericVector tau, NumericVector z, Nullable<double> rhor, Nullable<double> mur, Nullable<double> sigmar, Nullable<double> rhos, Nullable<double> mus, Nullable<double> sigmas);
RcppExport SEXP _GregsOUPR6_RcppOUPMLNMStart(SEXP tauSEXP, SEXP zSEXP, SEXP rhorSEXP, SEXP murSEXP, SEXP sigmarSEXP, SEXP rhosSEXP, SEXP musSEXP, SEXP sigmasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type rhor(rhorSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type mur(murSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type sigmar(sigmarSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type rhos(rhosSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type mus(musSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type sigmas(sigmasSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMLNMStart(tau, z, rhor, mur, sigmar, rhos, mus, sigmas));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMLNelderMead
NumericVector RcppOUPMLNelderMead(NumericVector tau, NumericVector z, NumericVector& theta, NumericVector& steps);
RcppExport SEXP _GregsOUPR6_RcppOUPMLNelderMead(SEXP tauSEXP, SEXP zSEXP, SEXP thetaSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type steps(stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMLNelderMead(tau, z, theta, steps));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMLGoodnessOfFit
NumericMatrix RcppOUPMLGoodnessOfFit(NumericVector tau, NumericVector z, double lnL, double alpha);
RcppExport SEXP _GregsOUPR6_RcppOUPMLGoodnessOfFit(SEXP tauSEXP, SEXP zSEXP, SEXP lnLSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type lnL(lnLSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMLGoodnessOfFit(tau, z, lnL, alpha));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMLLikelihoodRatioTest
NumericVector RcppOUPMLLikelihoodRatioTest(double lnL, double alpha, double m, double lnLr);
RcppExport SEXP _GregsOUPR6_RcppOUPMLLikelihoodRatioTest(SEXP lnLSEXP, SEXP alphaSEXP, SEXP mSEXP, SEXP lnLrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lnL(lnLSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type lnLr(lnLrSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMLLikelihoodRatioTest(lnL, alpha, m, lnLr));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCMinMax
NumericVector RcppOUPMCMinMax(NumericVector matPaths);
RcppExport SEXP _GregsOUPR6_RcppOUPMCMinMax(SEXP matPathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type matPaths(matPathsSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCMinMax(matPaths));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCStandardNormal
NumericMatrix RcppOUPMCStandardNormal(int64_t m, int64_t skip, int64_t paths, uint64_t seed);
RcppExport SEXP _GregsOUPR6_RcppOUPMCStandardNormal(SEXP mSEXP, SEXP skipSEXP, SEXP pathsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int64_t >::type m(mSEXP);
    Rcpp::traits::input_parameter< int64_t >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< int64_t >::type paths(pathsSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCStandardNormal(m, skip, paths, seed));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCForwardPathRungeKutta
NumericMatrix RcppOUPMCForwardPathRungeKutta(NumericMatrix stdnorm, double x, std::size_t m, std::size_t skip, double dt, double rho, double mu, double sigma);
RcppExport SEXP _GregsOUPR6_RcppOUPMCForwardPathRungeKutta(SEXP stdnormSEXP, SEXP xSEXP, SEXP mSEXP, SEXP skipSEXP, SEXP dtSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type stdnorm(stdnormSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type m(mSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCForwardPathRungeKutta(stdnorm, x, m, skip, dt, rho, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCBackwardPathRungeKutta
NumericMatrix RcppOUPMCBackwardPathRungeKutta(NumericMatrix stdnorm, double y, std::size_t m, std::size_t skip, double ds, double rho, double mu, double sigma);
RcppExport SEXP _GregsOUPR6_RcppOUPMCBackwardPathRungeKutta(SEXP stdnormSEXP, SEXP ySEXP, SEXP mSEXP, SEXP skipSEXP, SEXP dsSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type stdnorm(stdnormSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::size_t >::type m(mSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< double >::type ds(dsSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCBackwardPathRungeKutta(stdnorm, y, m, skip, ds, rho, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCBoundedPathRungeKutta
NumericMatrix RcppOUPMCBoundedPathRungeKutta(NumericMatrix stdnorm, double k, double x, std::size_t m, std::size_t skip, double dt, double rho, double mu, double sigma);
RcppExport SEXP _GregsOUPR6_RcppOUPMCBoundedPathRungeKutta(SEXP stdnormSEXP, SEXP kSEXP, SEXP xSEXP, SEXP mSEXP, SEXP skipSEXP, SEXP dtSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type stdnorm(stdnormSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type m(mSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCBoundedPathRungeKutta(stdnorm, k, x, m, skip, dt, rho, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCForwardPathIntegralEquation
NumericMatrix RcppOUPMCForwardPathIntegralEquation(NumericMatrix stdnorm, double x, std::size_t m, std::size_t skip, double dt, double rho, double mu, double sigma);
RcppExport SEXP _GregsOUPR6_RcppOUPMCForwardPathIntegralEquation(SEXP stdnormSEXP, SEXP xSEXP, SEXP mSEXP, SEXP skipSEXP, SEXP dtSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type stdnorm(stdnormSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type m(mSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCForwardPathIntegralEquation(stdnorm, x, m, skip, dt, rho, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCBackwardPathIntegralEquation
NumericMatrix RcppOUPMCBackwardPathIntegralEquation(NumericMatrix stdnorm, double y, std::size_t m, std::size_t skip, double ds, double rho, double mu, double sigma);
RcppExport SEXP _GregsOUPR6_RcppOUPMCBackwardPathIntegralEquation(SEXP stdnormSEXP, SEXP ySEXP, SEXP mSEXP, SEXP skipSEXP, SEXP dsSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type stdnorm(stdnormSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::size_t >::type m(mSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< double >::type ds(dsSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCBackwardPathIntegralEquation(stdnorm, y, m, skip, ds, rho, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCBoundedPathIntegralEquation
NumericMatrix RcppOUPMCBoundedPathIntegralEquation(NumericMatrix stdnorm, double k, double x, std::size_t m, std::size_t skip, double dt, double rho, double mu, double sigma);
RcppExport SEXP _GregsOUPR6_RcppOUPMCBoundedPathIntegralEquation(SEXP stdnormSEXP, SEXP kSEXP, SEXP xSEXP, SEXP mSEXP, SEXP skipSEXP, SEXP dtSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type stdnorm(stdnormSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type m(mSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCBoundedPathIntegralEquation(stdnorm, k, x, m, skip, dt, rho, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCForwardCountY
NumericMatrix RcppOUPMCForwardCountY(NumericMatrix forward, NumericVector y, double psi);
RcppExport SEXP _GregsOUPR6_RcppOUPMCForwardCountY(SEXP forwardSEXP, SEXP ySEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type forward(forwardSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCForwardCountY(forward, y, psi));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCBackwardCountX
NumericMatrix RcppOUPMCBackwardCountX(NumericMatrix backward, NumericVector x, double phi, double rho, double r, double ds);
RcppExport SEXP _GregsOUPR6_RcppOUPMCBackwardCountX(SEXP backwardSEXP, SEXP xSEXP, SEXP phiSEXP, SEXP rhoSEXP, SEXP rSEXP, SEXP dsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type backward(backwardSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type ds(dsSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCBackwardCountX(backward, x, phi, rho, r, ds));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCForwardCountT
NumericMatrix RcppOUPMCForwardCountT(NumericMatrix forward, double k, double dt, double rho, double mu, double sigma, double Ppct);
RcppExport SEXP _GregsOUPR6_RcppOUPMCForwardCountT(SEXP forwardSEXP, SEXP kSEXP, SEXP dtSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP PpctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type forward(forwardSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type Ppct(PpctSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCForwardCountT(forward, k, dt, rho, mu, sigma, Ppct));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCBoundedCountT
NumericMatrix RcppOUPMCBoundedCountT(NumericVector fpt, std::size_t m, double dt, double Ppct);
RcppExport SEXP _GregsOUPR6_RcppOUPMCBoundedCountT(SEXP fptSEXP, SEXP mSEXP, SEXP dtSEXP, SEXP PpctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fpt(fptSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type Ppct(PpctSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCBoundedCountT(fpt, m, dt, Ppct));
    return rcpp_result_gen;
END_RCPP
}
// RcppOUPMCHeatCountZ
NumericMatrix RcppOUPMCHeatCountZ(NumericMatrix matPaths, NumericVector z);
RcppExport SEXP _GregsOUPR6_RcppOUPMCHeatCountZ(SEXP matPathsSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type matPaths(matPathsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOUPMCHeatCountZ(matPaths, z));
    return rcpp_result_gen;
END_RCPP
}
// RcppParallelInstalled
bool RcppParallelInstalled();
RcppExport SEXP _GregsOUPR6_RcppParallelInstalled() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(RcppParallelInstalled());
    return rcpp_result_gen;
END_RCPP
}
// RcppsitmoInstalled
bool RcppsitmoInstalled();
RcppExport SEXP _GregsOUPR6_RcppsitmoInstalled() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(RcppsitmoInstalled());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GregsOUPR6_RcppOUPADrift", (DL_FUNC) &_GregsOUPR6_RcppOUPADrift, 3},
    {"_GregsOUPR6_RcppOUPADiffusion", (DL_FUNC) &_GregsOUPR6_RcppOUPADiffusion, 2},
    {"_GregsOUPR6_RcppOUPAMean", (DL_FUNC) &_GregsOUPR6_RcppOUPAMean, 6},
    {"_GregsOUPR6_RcppOUPAVariance", (DL_FUNC) &_GregsOUPR6_RcppOUPAVariance, 5},
    {"_GregsOUPR6_RcppOUPADensity", (DL_FUNC) &_GregsOUPR6_RcppOUPADensity, 7},
    {"_GregsOUPR6_RcppOUPAProbability", (DL_FUNC) &_GregsOUPR6_RcppOUPAProbability, 8},
    {"_GregsOUPR6_RcppOUPADoubleIntegral", (DL_FUNC) &_GregsOUPR6_RcppOUPADoubleIntegral, 8},
    {"_GregsOUPR6_RcppOUPAOption", (DL_FUNC) &_GregsOUPR6_RcppOUPAOption, 11},
    {"_GregsOUPR6_RcppOUPAOptionEnvelope", (DL_FUNC) &_GregsOUPR6_RcppOUPAOptionEnvelope, 11},
    {"_GregsOUPR6_RcppOUPAdOOdsZero", (DL_FUNC) &_GregsOUPR6_RcppOUPAdOOdsZero, 11},
    {"_GregsOUPR6_RcppOUPADecisionThreshold", (DL_FUNC) &_GregsOUPR6_RcppOUPADecisionThreshold, 8},
    {"_GregsOUPR6_RcppOUPAObligation", (DL_FUNC) &_GregsOUPR6_RcppOUPAObligation, 10},
    {"_GregsOUPR6_RcppOUPAPassageTimeModeMedianMean", (DL_FUNC) &_GregsOUPR6_RcppOUPAPassageTimeModeMedianMean, 8},
    {"_GregsOUPR6_RcppOUPAPassageTimePercentiles", (DL_FUNC) &_GregsOUPR6_RcppOUPAPassageTimePercentiles, 9},
    {"_GregsOUPR6_RcppOUPAPassageTimeDensity", (DL_FUNC) &_GregsOUPR6_RcppOUPAPassageTimeDensity, 9},
    {"_GregsOUPR6_RcppOUPAPassageTimeProbability", (DL_FUNC) &_GregsOUPR6_RcppOUPAPassageTimeProbability, 9},
    {"_GregsOUPR6_RcppOUPFDDrift", (DL_FUNC) &_GregsOUPR6_RcppOUPFDDrift, 3},
    {"_GregsOUPR6_RcppOUPFDDiffusion", (DL_FUNC) &_GregsOUPR6_RcppOUPFDDiffusion, 2},
    {"_GregsOUPR6_RcppOUPFDTerminalValue_Linear", (DL_FUNC) &_GregsOUPR6_RcppOUPFDTerminalValue_Linear, 3},
    {"_GregsOUPR6_RcppOUPFDTerminalValue_Degenerate", (DL_FUNC) &_GregsOUPR6_RcppOUPFDTerminalValue_Degenerate, 4},
    {"_GregsOUPR6_RcppOUPFDTerminalValue_Stepped", (DL_FUNC) &_GregsOUPR6_RcppOUPFDTerminalValue_Stepped, 5},
    {"_GregsOUPR6_RcppOUPFDTerminalValue_Kinked", (DL_FUNC) &_GregsOUPR6_RcppOUPFDTerminalValue_Kinked, 5},
    {"_GregsOUPR6_RcppOUPFDTerminalValue_Butterfly", (DL_FUNC) &_GregsOUPR6_RcppOUPFDTerminalValue_Butterfly, 6},
    {"_GregsOUPR6_RcppOUPFDTerminalValue_Mitscherlich", (DL_FUNC) &_GregsOUPR6_RcppOUPFDTerminalValue_Mitscherlich, 5},
    {"_GregsOUPR6_RcppOUPFDTerminalValue_Gompertz", (DL_FUNC) &_GregsOUPR6_RcppOUPFDTerminalValue_Gompertz, 5},
    {"_GregsOUPR6_RcppOUPFDTerminalValue_Logistic", (DL_FUNC) &_GregsOUPR6_RcppOUPFDTerminalValue_Logistic, 5},
    {"_GregsOUPR6_RcppOUPFDTerminalValue_Transcendental", (DL_FUNC) &_GregsOUPR6_RcppOUPFDTerminalValue_Transcendental, 6},
    {"_GregsOUPR6_RcppOUPFDTerminalValue_YieldIndex", (DL_FUNC) &_GregsOUPR6_RcppOUPFDTerminalValue_YieldIndex, 6},
    {"_GregsOUPR6_RcppOUPFDOption", (DL_FUNC) &_GregsOUPR6_RcppOUPFDOption, 9},
    {"_GregsOUPR6_RcppOUPFDOptionEnvelope", (DL_FUNC) &_GregsOUPR6_RcppOUPFDOptionEnvelope, 9},
    {"_GregsOUPR6_RcppOUPFDDecisionThreshold", (DL_FUNC) &_GregsOUPR6_RcppOUPFDDecisionThreshold, 4},
    {"_GregsOUPR6_RcppOUPMLLogLikelihood", (DL_FUNC) &_GregsOUPR6_RcppOUPMLLogLikelihood, 5},
    {"_GregsOUPR6_RcppOUPMLNMStart", (DL_FUNC) &_GregsOUPR6_RcppOUPMLNMStart, 8},
    {"_GregsOUPR6_RcppOUPMLNelderMead", (DL_FUNC) &_GregsOUPR6_RcppOUPMLNelderMead, 4},
    {"_GregsOUPR6_RcppOUPMLGoodnessOfFit", (DL_FUNC) &_GregsOUPR6_RcppOUPMLGoodnessOfFit, 4},
    {"_GregsOUPR6_RcppOUPMLLikelihoodRatioTest", (DL_FUNC) &_GregsOUPR6_RcppOUPMLLikelihoodRatioTest, 4},
    {"_GregsOUPR6_RcppOUPMCMinMax", (DL_FUNC) &_GregsOUPR6_RcppOUPMCMinMax, 1},
    {"_GregsOUPR6_RcppOUPMCStandardNormal", (DL_FUNC) &_GregsOUPR6_RcppOUPMCStandardNormal, 4},
    {"_GregsOUPR6_RcppOUPMCForwardPathRungeKutta", (DL_FUNC) &_GregsOUPR6_RcppOUPMCForwardPathRungeKutta, 8},
    {"_GregsOUPR6_RcppOUPMCBackwardPathRungeKutta", (DL_FUNC) &_GregsOUPR6_RcppOUPMCBackwardPathRungeKutta, 8},
    {"_GregsOUPR6_RcppOUPMCBoundedPathRungeKutta", (DL_FUNC) &_GregsOUPR6_RcppOUPMCBoundedPathRungeKutta, 9},
    {"_GregsOUPR6_RcppOUPMCForwardPathIntegralEquation", (DL_FUNC) &_GregsOUPR6_RcppOUPMCForwardPathIntegralEquation, 8},
    {"_GregsOUPR6_RcppOUPMCBackwardPathIntegralEquation", (DL_FUNC) &_GregsOUPR6_RcppOUPMCBackwardPathIntegralEquation, 8},
    {"_GregsOUPR6_RcppOUPMCBoundedPathIntegralEquation", (DL_FUNC) &_GregsOUPR6_RcppOUPMCBoundedPathIntegralEquation, 9},
    {"_GregsOUPR6_RcppOUPMCForwardCountY", (DL_FUNC) &_GregsOUPR6_RcppOUPMCForwardCountY, 3},
    {"_GregsOUPR6_RcppOUPMCBackwardCountX", (DL_FUNC) &_GregsOUPR6_RcppOUPMCBackwardCountX, 6},
    {"_GregsOUPR6_RcppOUPMCForwardCountT", (DL_FUNC) &_GregsOUPR6_RcppOUPMCForwardCountT, 7},
    {"_GregsOUPR6_RcppOUPMCBoundedCountT", (DL_FUNC) &_GregsOUPR6_RcppOUPMCBoundedCountT, 4},
    {"_GregsOUPR6_RcppOUPMCHeatCountZ", (DL_FUNC) &_GregsOUPR6_RcppOUPMCHeatCountZ, 2},
    {"_GregsOUPR6_RcppParallelInstalled", (DL_FUNC) &_GregsOUPR6_RcppParallelInstalled, 0},
    {"_GregsOUPR6_RcppsitmoInstalled", (DL_FUNC) &_GregsOUPR6_RcppsitmoInstalled, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_GregsOUPR6(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
