# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Analytical_Rcpp functions for calculating an Ornstein-Uhlenbeck Process
#'
#' @description
#' Calculations for the R6 class 'Analytical', with parallel processing.
#'
#' @details # Note on Notation
#' The notation for times and states is confusing.  Times can be either
#'  fixed or variable.  States can be either observed or stochastic.  As
#'  arguments to the functions, they can be either scalars or vectors.
#'  Functions in Rcpp have local scope and don't get confused.  But this
#'  documentation is constructed in the R manner, assuming all arguments are
#'  globally defined.
#'
#' Simple arguments have globally unique names, but times and states have
#'  different roles, depending upon the problem.  Initial value problems, like
#'  probabilities, have an initial time, an initial state, a time variable and
#'  a stochastic state.  Terminal value problems, like options, have a terminal
#'  time, a terminal state, a time variable and a stochastic state.  But initial
#'  value and terminal value problems are not different problems.  They are
#'  governed by the same stochastic differential and integral equations. Times
#'  and states cannot swap places in the formulas without violating the differential
#'  and integral equations.
#'
#' Hence, we adopt Kolmogorov's notation with backward variables s and x and
#'  forward variables t and y.  In initial value problems, s is fixed, x is
#'  observed, t is variable and y is stochastic.  In terminal value problems,
#'  t and y are fixed, s is variable and x is stochastic.  But s, x, t and y
#'  occupy their same places in all formulas.
#'
#' The Rcpp functions aren't confused by this, but how can people know how to
#'  enter the arguments?  The time and state arguments listed first are vectors.
#'  The time and state arguments listed second are scalars.  For example in
#'  RcppOUPAProbability(t,y,s,x,...), t and y are vectors and s and x are scalars.
#'  In RcppOUPAOption(s,x,t,y,...), s and x are vectors and t and y are scalars.
#'
#' Finally, the state z is also schizophrenic.  In the stochastic differential
#'  equation, it represents either state x or state y.  In passage times, it
#'  is an optional argument for alternate initial states x.
#'
#' @details # Notes on Values
#' Return values are vectors and matrices allocated in Rcpp.  The dimensions are
#'  shown for information.  Of course, do not include them in R calls.  For example:
#'
#'     g <- RcppOUPADrift(z,rho,mu)
#'
#' The return values:
#'
#'     g(n)
#'     h2(n)
#'
#'  are vectors for drift and diffusion of the same dimension as z.
#'
#' The return values:
#'
#'     Gt(m+1)
#'     H2t(m+1)
#'
#'  are vectors with means G and Variances H2 followed by a time, teps.  For means,
#'  teps is the time until convergence to within epsilon of the location.  For Variances,
#'  teps is the time until convergence to within epsilon of the asymptotic variance.
#'
#' The return values:
#'
#'     p(m,n)
#'     P(m,n)
#'     PP(m,n)
#'
#'  are matrices of Transition Densities, Transition Probabilities and Double
#'  Integrals  with rows for t and columns for y.
#'
#' The return value:
#'
#'     OO(m,n)
#'
#'  is a matrix of Options with rows for s and columns for x.
#'
#' The return value:
#'
#'     OOs(2,n)
#'
#'  is a matrix with two row vectors for option prices and corresponding times
#'  along the option envelope.  It is subset in R as:
#'
#'     OOhat <- OOs[1,,drop=FALSE]
#'     shat <- OOs[2,,drop=FALSE]
#'
#'  where t is the terminal time.
#'
#' The return value:
#'
#'     dOOdszero(4,n+3)
#'
#'  is a matrix of four row vectors followed by three column vectors.  The row vectors
#'  are for option prices and times where the derivatives of option prices with
#'  respect to times equal zero.  The first and second rows are for option prices.
#'  and times where option prices are convex in time. The third and fourth rows are
#'  where option prices are concave in time.  The three column vectors are a patch to
#'  connect the row vectors where the surface of the option prices transform from
#'  convex to concave.  Within the patch, the first row has option prices, the second
#'  row has times and the third row has states.  The matrix is subset in R as:
#'
#'     dOOdsconvex <- dOOdszero[1:2,1:n,drop=FALSE]
#'     dOOdsconcave <- dOOdszero[3:4,1:n,drop=FALSE]
#'     dOOdspatch <- dOOdszero[1:3,(n+1):(n+3),drop=FALSE]
#'
#' This return value is mostly a curiosity. Plotting it with the option envelope shows
#'  that, at the decision threshold, the option envelope jumps over the convexity to
#'  reach the terminal value.
#'
#' The return value:
#'
#'     kOO(2)
#'
#'  is a vector with two elements for the state at the decision threshold and
#'  the option price at that state.  It is subset in R as:
#'
#'     k <- kOO[1]
#'     OOhat <- kOO[2]
#'
#' The return values:
#'
#'     tmmmtmmmx(3,n+1)
#'     tpcttpctx(3,n+1)
#'
#'  are matrices of three row vectors.  The rows are for the mode, median and mean
#'  or for the lower, median and upper percentiles.  For each row, the first n
#'  elements are for the alternate initial starting values, z.  The last element
#'  is for the initial state x.  The matrices are subset in R as:
#'
#'     tmode <- tmmmtmmmx[1,n+1,drop=FALSE]
#'     tmedian <- tmmmtmmmx[2,n+1,drop=FALSE]
#'     tmean <- tmmmtmmmx[3,n+1,drop=FALSE]
#'     tmodes <- tmmmtmmmx[1,1:n,drop=FALSE]
#'     tmedians <- tmmmtmmmx[2,1:n,drop=FALSE]
#'     tmeans <- tmmmtmmmx[3,1:n,drop=FALSE]
#'
#'     tlower <- tpcttpctx[1,n+1,drop=FALSE]
#'     tmedian <- tpcttpctx[2,n+1,drop=FALSE]
#'     tupper <- tpcttpctx[3,n+1,drop=FALSE]
#'     tlowers <- tpcttpctx[1,1:n,drop=FALSE]
#'     tmedians <- tpcttpctx[2,1:n,drop=FALSE]
#'     tuppers <- tpcttpctx[3,1:n,drop=FALSE]
#'
#' The alternate initial states, z, are optional.  If omitted, the return values
#'  are vectors for the initial state, x, subset in R as:
#'
#'     tmode <- tmmmtmmmx[1]
#'     tmedian <- tmmmtmmmx[2]
#'     tmean <- tmmmtmmmx[3]
#'
#'     tlower <- tpcttpctx[1]
#'     tmedian <- tpcttpctx[2]
#'     tupper <- tpcttpctx[3]
#'
#' The return values:
#'
#'     ptptx(m,n+1)
#'     PtPtx(m,n+1)
#'
#'  are matrices plus column vectors.  A matrix contains the passage time
#'  densities or probabilities for alternate initial states, z.  The last
#'  column is the passage time density or probability at the initial state, x.
#'  The matrices are subset in R as:
#'
#'     pt <- ptptx[,1:n,drop=FALSE]
#'     ptx <- ptptx[,n+1,drop=FALSE]
#'     Pt <- PtPtx[,1:n,drop=FALSE]
#'     Ptx <- PtPtx[,n+1,drop=FALSE]
#'
#' The alternate initial states, z, are optional.  If omitted, the return values
#'  are vectors for the initial state, x:
#'
#'     ptptx(m)
#'     PtPtx(m)
#'
#' These do not need to be subset in R.
#'
#' @details # Discussion
#' First, the analytical formulas were implemented in R6 as a single-threaded
#'  application.  Then the R6 code was translated into Rcpp sequential code.
#'  Then it was translated into RcppParallel code.  The R6 single-threaded
#'  code was archived and only the Rcpp and RcppParallel codes remain.
#'
#' Below are microbenchmark median times to calculate 40,000 results.
#'  Calculations are on an i7 CPU with 12 threads running at a maximum speed
#'  of 4.5 GHz.
#'
#'     Unit: milliseconds             R6      R6+           R6+
#'               function  single-thread     Rcpp  RcppParallel
#'     --------------------------------------------------------
#'                Density        225.656   7.2685        1.1125
#'            Probability       5412.144  11.6550        1.5818
#'         DoubleIntegral       6909.977  21.6572        2.6955
#'                 Option       5187.448  24.1113        2.9611
#'             Obligation        347.682   3.9241        0.7776
#'
#' R6+Rcpp calculates from 31.0 to 464.4 times faster than R6 single-thread.
#'  R6+RcppParallel calculates from 5.0 to 8.1 times faster than R6+Rcpp and
#'  from 202.8 to 3421.5 times faster than R6 single-thread.
#'
#' For 40,000 Options, the Option Envelope requires 200 searches in the time
#'  direction and the Decision Threshold is a sequential search in the state
#'  direction with nested searches in the time direction.  There is no parallel
#'  code for the Decision Threshold.  Below are the median times:
#'
#'     Unit: milliseconds             R6      R6+           R6+
#'               function  single-thread     Rcpp  RcppParallel
#'     --------------------------------------------------------
#'         OptionEnvelope        651.259   3.7036        0.7437
#'      DecisionThreshold        236.470   1.3693
#'
#' R6+Rcpp calculates 174.5 and 172.7 times faster than R6 single-thread.
#'  R6+RcppParallel calculates 5.0 times faster than R6+Rcpp and 875.7 times
#'  faster than R6 single-thread.
#'
#' Passage Time calculations are expensive.  The mode, median and percentiles
#'  are searches over densities and probabilities.  The mean is a Gaussian
#'  quadrature.  Below are the median times for 10,000 Passage Times:
#'
#'     Unit: milliseconds                    R6      R6+           R6+
#'                      function  single-thread     Rcpp  RcppParallel
#'     ---------------------------------------------------------------
#'     PassageTimeModeMedianMean       4576.543  22.3153        2.9293
#'        PassageTimePercentiles       4246.912  17.4183        2.3781
#'            PassageTimeDensity       2091.740  11.1987        1.6769
#'        PassageTimeProbability       3217.157  11.2643        1.5363
#'
#' R6+Rcpp calculates from 186.8 to 285.6 times faster than R6 single-thread.
#'  R6+RcppParallel calculates from 6.7 to 7.6 times faster than R6+Rcpp and
#'  from 1247.4 to 2094.1 times faster than R6 single-thread.
#'
#' After Rcpp versions of the functions were coded, all but DecisionThreshold
#'  were translated into RcppParallel versions.  RccpParallel uses Intel's
#'  Threading Building Blocks (TBB) on the CPU.  Unlike parallel processing on
#'  a GPU or accelerator, memory isn't copied and there is less overhead.  On
#'  trivially small problems, sequential versions calculate faster.  On large
#'  problems, parallel versions calculate several times faster.
#'
#' RcppParallel is an optional package.  If it is installed, it will be used.
#'  Function RcppParallelInstalled() will enquire whether code is compiled with
#'  RcppParallel or has fallen back to Rcpp.
#'
#' @details # From the Console
#' These functions are available in R, the RStudio console and RShiny apps. As
#'  an example, a calculation of option prices would be:
#'
#'     s <- seq(from=30,to=10,by=-0.1)
#'     x <- seq(from=-40,to=60,by=0.5)
#'     OO <- RcppOUPAOption(s,x,30,0,0.5,15,15,0.05,1,0,0)
#'
#' Calling functions directly from the console is slightly faster than
#'  calling them indirectly through R6 objects.  Here are microbenchmark
#'  median times for comparison with some of the previous results:
#'
#'     Unit: milliseconds           R6+        Console
#'               function  RcppParallel   RcppParallel
#'     -----------------------------------------------
#'                Density        1.1125         0.9925
#'            Probability        1.5818         1.4358
#'        Double Integral        2.6955         2.5753
#'                 Option        2.9611         2.8299
#'             Obligation        0.7776         0.5291
#'
#' The extra times taken by the R6 object are fractions of a millisecond.
#'  Although slower, the R6 object has advantages over the console. All inputs
#'  are optional and are coordinated across functions.  Enter an input once
#'  and calculate several outputs.  The R6 object is reactive.  In other words,
#'  it stores the inputs and outputs and maps inputs to outputs.  If an input
#'  changes, dependent outputs are nullified and will be recalculated, as
#'  requested, but nothing is calculated twice.  The console stores outputs in
#'  the global environment, but there is no map of inputs to outputs.  Outputs
#'  can be stale.  Another advantage of the R6 object is predefined plots with
#'  Plotly. The same simulation can plotted different ways without recalculation.
#'
#' Potentially, the Rcpp functions could be imported into other packages.
#'
#' @name Analytical_Rcpp
NULL

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPADrift(z,rho,mu)
#' @param  z   vector of states or optional vector of alternate initial states
#' @param  rho rate parameter 0<=rho<inf
#' @param  mu  location parameter -inf<mu<inf
#' @return g(n) <- RcppOUPADrift()
#' @export
RcppOUPADrift <- function(z, rho, mu) {
    .Call(`_GregsOUPR6_RcppOUPADrift`, z, rho, mu)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPADiffusion(z,sigma)
#' @param  z     vector of states or optional vector of alternate initial states
#' @param  sigma scale parameter -inf<sigma<inf
#' @return h2(n) <- RcppOUPADiffusion()
#' @export
RcppOUPADiffusion <- function(z, sigma) {
    .Call(`_GregsOUPR6_RcppOUPADiffusion`, z, sigma)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPAMean(t,s,x,rho,mu,eps)
#' @param  t   terminal time or vector of forward times
#' @param  s   initial time or vector of backward times
#' @param  x   initial state or vector of backward states
#' @param  rho rate parameter 0<=rho<inf
#' @param  mu  location parameter -inf<mu<inf
#' @param  eps proportion remaining after convergence 0<=eps<=1
#' @return Gt(m+1) <- RcppOUPAMean()
#' @export
RcppOUPAMean <- function(t, s, x, rho, mu, eps) {
    .Call(`_GregsOUPR6_RcppOUPAMean`, t, s, x, rho, mu, eps)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPAVariance(t,s,rho,sigma,eps)
#' @param  t     terminal time or vector of forward times
#' @param  s     initial time or vector of backward times
#' @param  rho   rate parameter 0<=rho<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @param  eps   proportion remaining after convergence 0<=eps<=1
#' @return H2t(m+1) <- RcppOUPAVariance()
#' @export
RcppOUPAVariance <- function(t, s, rho, sigma, eps) {
    .Call(`_GregsOUPR6_RcppOUPAVariance`, t, s, rho, sigma, eps)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPADensity(t,y,s,x,rho,mu,sigma)
#' @param  t     terminal time or vector of forward times
#' @param  y     terminal state or vector of forward states
#' @param  s     initial time or vector of backward times
#' @param  x     initial state or vector of backward states
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @return p(m,n) <- RcppOUPADensity()
#' @export
RcppOUPADensity <- function(t, y, s, x, rho, mu, sigma) {
    .Call(`_GregsOUPR6_RcppOUPADensity`, t, y, s, x, rho, mu, sigma)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPAProbability(t,y,s,x,rho,mu,sigma,psi)
#' @param  t     terminal time or vector of forward times
#' @param  y     terminal state or vector of forward states
#' @param  s     initial time or vector of backward times
#' @param  x     initial state or vector of backward states
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @param  psi   <=0 for integral -inf to y, >0 for integral y to inf
#' @return P(m,n) <- RcppOUPAProbability()
#' @export
RcppOUPAProbability <- function(t, y, s, x, rho, mu, sigma, psi) {
    .Call(`_GregsOUPR6_RcppOUPAProbability`, t, y, s, x, rho, mu, sigma, psi)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPADoubleIntegral(t,y,s,x,rho,mu,sigma,psi)
#' @param  t     terminal time or vector of forward times
#' @param  y     terminal state or vector of forward states
#' @param  s     initial time or vector of backward times
#' @param  x     initial state or vector of backward states
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @param  psi   <=0 for integral -inf to y, >0 for integral y to inf
#' @return PP(m,n) <- RcppOUPADoubleIntegral()
#' @export
RcppOUPADoubleIntegral <- function(t, y, s, x, rho, mu, sigma, psi) {
    .Call(`_GregsOUPR6_RcppOUPADoubleIntegral`, t, y, s, x, rho, mu, sigma, psi)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPAOption(s,x,t,y,rho,mu,sigma,r,phi,b,c)
#' @param  s     initial time or vector of backward times
#' @param  x     initial state or vector of backward states
#' @param  t     terminal time or vector of forward times
#' @param  y     terminal state or vector of forward states
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @param  r     discount rate -inf<r<inf
#' @param  phi   <=0 for integral -inf to x, >0 for integral x to inf
#' @param  b     lump-sum benefit for entry option
#' @param  c     lump-sum cost for exit option
#' @return OO(m,n) <- RcppOUPAOption()
#' @export
RcppOUPAOption <- function(s, x, t, y, rho, mu, sigma, r, phi, b, c) {
    .Call(`_GregsOUPR6_RcppOUPAOption`, s, x, t, y, rho, mu, sigma, r, phi, b, c)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPAOptionEnvelope(s,x,t,y,rho,mu,sigma,r,phi,b,c)
#' @param  s     initial time or vector of backward times
#' @param  x     initial state or vector of backward states
#' @param  t     terminal time or vector of forward times
#' @param  y     terminal state or vector of forward states
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @param  r     discount rate -inf<r<inf
#' @param  phi   <=0 for integral -inf to x, >0 for integral x to inf
#' @param  b     lump-sum benefit for entry option
#' @param  c     lump-sum cost for exit option
#' @return OOs(2,n) <- RcppOUPAOptionEnvelope()
#' @export
RcppOUPAOptionEnvelope <- function(s, x, t, y, rho, mu, sigma, r, phi, b, c) {
    .Call(`_GregsOUPR6_RcppOUPAOptionEnvelope`, s, x, t, y, rho, mu, sigma, r, phi, b, c)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPAdOOdsZero(s,x,t,y,rho,mu,sigma,r,phi,b,c)
#' @param  s     initial time or vector of backward times
#' @param  x     initial state or vector of backward states
#' @param  t     terminal time or vector of forward times
#' @param  y     terminal state or vector of forward states
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @param  r     discount rate -inf<r<inf
#' @param  phi   <=0 for integral -inf to x, >0 for integral x to inf
#' @param  b     lump-sum benefit for entry option
#' @param  c     lump-sum cost for exit option
#' @return dOOdszero(4,n+3) <- RcppOUPAdOOdsZero()
#' @export
RcppOUPAdOOdsZero <- function(s, x, t, y, rho, mu, sigma, r, phi, b, c) {
    .Call(`_GregsOUPR6_RcppOUPAdOOdsZero`, s, x, t, y, rho, mu, sigma, r, phi, b, c)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPADecisionThreshold(y,rho,mu,sigma,r,phi,b,c)
#' @param  y     terminal state or vector of forward states
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @param  r     discount rate -inf<r<inf
#' @param  phi   <=0 for integral -inf to x, >0 for integral x to inf
#' @param  b     lump-sum benefit for entry option
#' @param  c     lump-sum cost for exit option
#' @return kOO(2) <- RcppOUPADecisionThreshold()
#' @export
RcppOUPADecisionThreshold <- function(y, rho, mu, sigma, r, phi, b, c) {
    .Call(`_GregsOUPR6_RcppOUPADecisionThreshold`, y, rho, mu, sigma, r, phi, b, c)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPAObligation(s,x,t,y,rho,mu,r,phi,b,c)
#' @param  s     initial time or vector of backward times
#' @param  x     initial state or vector of backward states
#' @param  t     terminal time or vector of forward times
#' @param  y     terminal state or vector of forward states
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  r     discount rate -inf<r<inf
#' @param  phi   <=0 for integral -inf to x, >0 for integral x to inf
#' @param  b     lump-sum benefit for entry option
#' @param  c     lump-sum cost for exit option
#' @return BC(m,n) <- RcppOUPAObligation()
#' @export
RcppOUPAObligation <- function(s, x, t, y, rho, mu, r, phi, b, c) {
    .Call(`_GregsOUPR6_RcppOUPAObligation`, s, x, t, y, rho, mu, r, phi, b, c)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPAPassageTimeModeMedianMean(k,s,x,omega,rho,mu,sigma,z)
#' @param  k     decision threshold
#' @param  s     initial time or vector of backward times
#' @param  x     initial state or vector of backward states
#' @param  omega degree of irreversibility 0<=omega<=1
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @param  z     vector of states or optional vector of alternate initial states
#' @return tmmmtmmmx(3,n+1) <- RcppOUPAPassageTimeModeMedianMean()
#' @export
RcppOUPAPassageTimeModeMedianMean <- function(k, s, x, omega, rho, mu, sigma, z = NULL) {
    .Call(`_GregsOUPR6_RcppOUPAPassageTimeModeMedianMean`, k, s, x, omega, rho, mu, sigma, z)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPAPassageTimePercentiles(k,s,x,omega,Ppct,rho,mu,sigma,z)
#' @param  k     decision threshold
#' @param  s     initial time or vector of backward times
#' @param  x     initial state or vector of backward states
#' @param  omega degree of irreversibility 0<=omega<=1
#' @param  Ppct  passage time probability for a percentile 0.01<=Ppct<=0.99
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @param  z     vector of states or optional vector of alternate initial states
#' @return tpcttpctx(3,n+1) <- RcppOUPAPassageTimePercentiles()
#' @export
RcppOUPAPassageTimePercentiles <- function(k, s, x, omega, Ppct, rho, mu, sigma, z = NULL) {
    .Call(`_GregsOUPR6_RcppOUPAPassageTimePercentiles`, k, s, x, omega, Ppct, rho, mu, sigma, z)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPAPassageTimeDensity(t,k,s,x,omega,rho,mu,sigma,z)
#' @param  t     terminal time or vector of forward times
#' @param  k     decision threshold
#' @param  s     initial time or vector of backward times
#' @param  x     initial state or vector of backward states
#' @param  omega degree of irreversibility 0<=omega<=1
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @param  z     vector of states or optional vector of alternate initial states
#' @return ptptx(m,n+1) <- RcppOUPAPassageTimeDensity()
#' @export
RcppOUPAPassageTimeDensity <- function(t, k, s, x, omega, rho, mu, sigma, z = NULL) {
    .Call(`_GregsOUPR6_RcppOUPAPassageTimeDensity`, t, k, s, x, omega, rho, mu, sigma, z)
}

#' @rdname Analytical_Rcpp
#' @usage  RcppOUPAPassageTimeProbability(t,k,s,x,omega,rho,mu,sigma,z)
#' @param  t     terminal time or vector of forward times
#' @param  k     decision threshold
#' @param  s     initial time or vector of backward times
#' @param  x     initial state or vector of backward states
#' @param  omega degree of irreversibility 0<=omega<=1
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @param  z     vector of states or optional vector of alternate initial states
#' @return PtPtx(m,n+1) <- RcppOUPAPassageTimeProbability()
#' @export
RcppOUPAPassageTimeProbability <- function(t, k, s, x, omega, rho, mu, sigma, z = NULL) {
    .Call(`_GregsOUPR6_RcppOUPAPassageTimeProbability`, t, k, s, x, omega, rho, mu, sigma, z)
}

#' @title FiniteDifference_Rcpp functions for numerical solutions of an
#'  Ornstein-Uhlenbeck Process
#'
#' @description
#' Calculations for the R6 class 'FiniteDifference', with sequential processing.
#'
#' @details # Notes on Values
#' Return values are vectors and matrices allocated in Rcpp.  The dimensions are
#'  shown for information.  Of course, do not include them in R calls.  For example:
#'
#'     g <- RcppOUPFDDrift(x,rho,mu)
#'
#' The return values:
#'
#'     g(n)
#'     h2(n)
#'     V(n)
#'
#'  are vectors of the same dimension as x.
#'
#' The return value:
#'
#'     c(m,n)
#'
#'  is a matrix with row dimension from s and column dimension from x.
#'
#' The return value:
#'
#'     env(2,n)
#'
#'  is a matrix with two row vectors for the option prices along the envelope
#'  and the corresponding times.  It is subset in R as:
#'
#'     OOenv <- env[1,]
#'     tsenv <- env[2,]
#'
#' The return value:
#'
#'     dec(2)
#'
#'  is a vector with two elements for the state at the decision threshold and
#'  the option price at that state.  It is subset in R as:
#'
#'     k <- dec[1]
#'     OOhat <- dec[2]
#'
#' @details # Discussion
#' First, the finite difference method was implemented in R6 as a
#'  single-threaded application.  Then the R6 code was translated into Rcpp
#'  sequential code.  The finite difference method steps backward in time.  For
#'  each time, it uses LU decomposition, followed by forward and backward
#'  substitution to solve matrices.  The finite difference method is inherently
#'  sequential.  Global searches for envelopes of option prices and decision
#'  thresholds are also sequential.  There is no parallel processing in this
#'  module.  The R6 single-threaded code has been archived, leaving the Rcpp code.
#'
#' Below are microbenchmark median times to calculate 400,000 Option Prices.
#'  Parameter skip=10 and only 40,000 Option Prices are reported.  Other rows
#'  show median times for the Option Envelope and the Decision Threshold.
#'  Calculations are on an i7 CPU with a maximum speed of 4.5 GHz.
#'
#'     Unit: milliseconds             R6     R6+
#'              function   single-thread    Rcpp
#'     -----------------------------------------
#'                Option        342.1143  7.7743
#'        OptionEnvelope        608.9655  4.6913
#'     DecisionThreshold          6.0607  0.1089
#'
#' The Option Envelope is an input into the calculation of the Decision Threshold.
#'  If the Decision Threshold is calculated from a standing start, add the two times.
#'  R6+Rcpp calculates from 44.0 to 129.8 times faster than R6 single-thread.
#'  The algorithms are not identical.  R6+Rcpp takes advantage of void subroutines
#'  and call-by-reference to manipulate vectors and matrices without copying.
#'
#' @details # From the Console
#' These functions are available in R, the RStudio console and RShiny apps.  For
#'  example, a  calculation of option prices would be:
#'
#'     s <- seq(from=30,to=10,by=-0.1)
#'     x <- seq(from=-40,to=60,by=0.5)
#'     n <- length(x)
#'     V <- vector("double",n)
#'     for(j in 1:n) { V[j] <- max(0,x[j]) }
#'     OO <- RcppOUPFDOption(s,x,V,0.05,0.5,10,0.5,15,15)
#'
#' Calling functions from the console is slightly faster than calling them
#'  through R6 objects.  The table below compares the R6+Rcpp median times
#'  above with the median times from the console:
#'
#'     Unit: milliseconds     R6+  Console
#'              function     Rcpp     Rcpp
#'     -----------------------------------
#'                Option   7.7743   7.3196
#'        OptionEnvelope   4.6913   4.5448
#'     DecisionThreshold   0.1089   0.0174
#'
#' There is less than half a millisecond time penalty for using the R6 object
#'  and it is much more convenient.  It is reactive.  In other words, it
#'  stores inputs and outputs and maps inputs to outputs.  Changing an input will
#'  nullify dependent outputs, eliminating any danger of reporting a stale output.
#'  Outputs are calculated only as needed and only once. Then they are reused.
#'  In plots using Plotly, for example.
#'
#' Potentially, the functions could be imported into other packages.
#'
#' @name FiniteDifference_Rcpp
NULL

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDDrift(x,rho,mu)
#' @param  x   vector of states
#' @param  rho rate parameter 0<=rho<inf
#' @param  mu  location parameter -inf<mu<inf
#' @return g(n) <- RcppOUPFDDrift()
#' @export
RcppOUPFDDrift <- function(x, rho, mu) {
    .Call(`_GregsOUPR6_RcppOUPFDDrift`, x, rho, mu)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDDiffusion(x,sigma)
#' @param  x     vector of states
#' @param  sigma scale parameter -inf<sigma<inf
#' @return h2(n) <- RcppOUPFDDiffusion()
#' @export
RcppOUPFDDiffusion <- function(x, sigma) {
    .Call(`_GregsOUPR6_RcppOUPFDDiffusion`, x, sigma)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDTerminalValue_Linear(x,xo,vs)
#' @param  x  vector of states
#' @param  xo   state at the intercept, step, kink or left wing
#' @param  vs slope
#' @return V(n) <- RcppOUPFDTerminalValue_Linear()
#' @export
RcppOUPFDTerminalValue_Linear <- function(x, xo, vs) {
    .Call(`_GregsOUPR6_RcppOUPFDTerminalValue_Linear`, x, xo, vs)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDTerminalValue_Degenerate(x,xo,Vmax,Vmin)
#' @param  x    vector of states
#' @param  xo   state at the intercept, step, kink or left wing
#' @param  Vmax maximum terminal value
#' @param  Vmin minimum terminal value
#' @return V(n) <- RcppOUPFDTerminalValue_Degenerate()
#' @export
RcppOUPFDTerminalValue_Degenerate <- function(x, xo, Vmax, Vmin) {
    .Call(`_GregsOUPR6_RcppOUPFDTerminalValue_Degenerate`, x, xo, Vmax, Vmin)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDTerminalValue_Stepped(x,xo,vs,Vmax,Vmin)
#' @param  x    vector of states
#' @param  xo   state at the intercept, step, kink or left wing
#' @param  vs   slope
#' @param  Vmax maximum terminal value
#' @param  Vmin minimum terminal value
#' @return V(n) <- RcppOUPFDTerminalValue_Stepped()
#' @export
RcppOUPFDTerminalValue_Stepped <- function(x, xo, vs, Vmax, Vmin) {
    .Call(`_GregsOUPR6_RcppOUPFDTerminalValue_Stepped`, x, xo, vs, Vmax, Vmin)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDTerminalValue_Kinked(x,xo,vs,Vmax,Vmin)
#' @param  x    vector of states
#' @param  xo   state at the intercept, step, kink or left wing
#' @param  vs   slope
#' @param  Vmax maximum terminal value
#' @param  Vmin minimum terminal value
#' @return V(n) <- RcppOUPFDTerminalValue_Kinked()
#' @export
RcppOUPFDTerminalValue_Kinked <- function(x, xo, vs, Vmax, Vmin) {
    .Call(`_GregsOUPR6_RcppOUPFDTerminalValue_Kinked`, x, xo, vs, Vmax, Vmin)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDTerminalValue_Butterfly(x,xo,xm,vs,Vmax,Vmin)
#' @param  x    vector of states
#' @param  xo   state at the intercept, step, kink or left wing
#' @param  xm   state at the maximum or right wing
#' @param  vs   slope
#' @param  Vmax maximum terminal value
#' @param  Vmin minimum terminal value
#' @return V(n) <- RcppOUPFDTerminalValue_Butterfly()
#' @export
RcppOUPFDTerminalValue_Butterfly <- function(x, xo, xm, vs, Vmax, Vmin) {
    .Call(`_GregsOUPR6_RcppOUPFDTerminalValue_Butterfly`, x, xo, xm, vs, Vmax, Vmin)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDTerminalValue_Mitscherlich(x,xo,vr,Vmax,Vmin)
#' @param  x    vector of states
#' @param  xo   state at the intercept, step, kink or left wing
#' @param  vr   rate of change
#' @param  Vmax maximum terminal value
#' @param  Vmin minimum terminal value
#' @return V(n) <- RcppOUPFDTerminalValue_Mitscherlich()
#' @export
RcppOUPFDTerminalValue_Mitscherlich <- function(x, xo, vr, Vmax, Vmin) {
    .Call(`_GregsOUPR6_RcppOUPFDTerminalValue_Mitscherlich`, x, xo, vr, Vmax, Vmin)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDTerminalValue_Gompertz(x,xi,vr,Vmax,Vmin)
#' @param  x    vector of states
#' @param  xi   state at the inflection point
#' @param  vr   rate of change
#' @param  Vmax maximum terminal value
#' @param  Vmin minimum terminal value
#' @return V(n) <- RcppOUPFDTerminalValue_Gompertz()
#' @export
RcppOUPFDTerminalValue_Gompertz <- function(x, xi, vr, Vmax, Vmin) {
    .Call(`_GregsOUPR6_RcppOUPFDTerminalValue_Gompertz`, x, xi, vr, Vmax, Vmin)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDTerminalValue_Logistic(x,xi,vr,Vmax,Vmin)
#' @param  x    vector of states
#' @param  xi   state at the inflection point
#' @param  vr   rate of change
#' @param  Vmax maximum terminal value
#' @param  Vmin minimum terminal value
#' @return V(n) <- RcppOUPFDTerminalValue_Logistic()
#' @export
RcppOUPFDTerminalValue_Logistic <- function(x, xi, vr, Vmax, Vmin) {
    .Call(`_GregsOUPR6_RcppOUPFDTerminalValue_Logistic`, x, xi, vr, Vmax, Vmin)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDTerminalValue_Transcendental(x,xo,xi,xm,Vmax,Vmin)
#' @param  x    vector of states
#' @param  xo   state at the intercept, step, kink or left wing
#' @param  xi   state at the inflection point
#' @param  xm   state at the maximum or right wing
#' @param  Vmax maximum terminal value
#' @param  Vmin minimum terminal value
#' @return V(n) <- RcppOUPFDTerminalValue_Transcendental()
#' @export
RcppOUPFDTerminalValue_Transcendental <- function(x, xo, xi, xm, Vmax, Vmin) {
    .Call(`_GregsOUPR6_RcppOUPFDTerminalValue_Transcendental`, x, xo, xi, xm, Vmax, Vmin)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDTerminalValue_YieldIndex(x,xo,xi,xm,Vmax,Vmin)
#' @param  x    vector of states
#' @param  xo   state at the intercept, step, kink or left wing
#' @param  xi   state at the inflection point
#' @param  xm   state at the maximum or right wing
#' @param  Vmax maximum terminal value
#' @param  Vmin minimum terminal value
#' @return V(n) <- RcppOUPFDTerminalValue_YieldIndex()
#' @export
RcppOUPFDTerminalValue_YieldIndex <- function(x, xo, xi, xm, Vmax, Vmin) {
    .Call(`_GregsOUPR6_RcppOUPFDTerminalValue_YieldIndex`, x, xo, xi, xm, Vmax, Vmin)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDOption(s,x,V,r,theta,skip,rho,mu,sigma)
#' @param  s     vector of times
#' @param  x     vector of states
#' @param  V     vector of terminal values
#' @param  r     discount rate 0<=r<inf
#' @param  theta weight of current time in time stepping 0.5<=theta<=1
#' @param  skip  subdivide time intervals but report at times s 1<=skip<=1000
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @return c(m,n) <- RcppOUPFDOption()
#' @export
RcppOUPFDOption <- function(s, x, V, r, theta, skip, rho, mu, sigma) {
    .Call(`_GregsOUPR6_RcppOUPFDOption`, s, x, V, r, theta, skip, rho, mu, sigma)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDOptionEnvelope(s,x,V,r,theta,skip,rho,mu,sigma)
#' @param  s     vector of times
#' @param  x     vector of states
#' @param  V     vector of terminal values
#' @param  r     discount rate 0<=r<inf
#' @param  theta weight of current time in time stepping 0.5<=theta<=1
#' @param  skip  subdivide time intervals but report at times s 1<=skip<=1000
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @return env(2,n) <- RcppOUPFDOptionEnvelope()
#' @export
RcppOUPFDOptionEnvelope <- function(s, x, V, r, theta, skip, rho, mu, sigma) {
    .Call(`_GregsOUPR6_RcppOUPFDOptionEnvelope`, s, x, V, r, theta, skip, rho, mu, sigma)
}

#' @rdname FiniteDifference_Rcpp
#' @usage  RcppOUPFDDecisionThreshold(x,V,OOenv,phi)
#' @param  x      vector of states
#' @param  V      vector of terminal values
#' @param  OOenv  envelope of option values
#' @param  phi    search direction for exit or entry options
#' @return dec(2) <- RcppOUPFDDecisionThreshold()
#' @export
RcppOUPFDDecisionThreshold <- function(x, V, OOenv, phi) {
    .Call(`_GregsOUPR6_RcppOUPFDDecisionThreshold`, x, V, OOenv, phi)
}

#' @title MaximumLikelihood_Rcpp functions to estimate an Ornstein-Uhlenbeck Process
#'
#' @description
#' Calculations for the R6 class 'MaximumLikelihood', with sequential and parallel
#'  processing.
#'
#' @details # Notes on Values
#' Return values are vectors and matrices allocated in Rcpp.  The dimensions are
#'  shown for information.  Of course, do not include them in R calls.  For example:
#'
#'     logL <- RcppOUPMLLogLikelihood(tau,z,rho,mu,sigma)
#'
#' The return value:
#'
#'     logL(4)
#'
#'  is a vector containing the LogLikelihood, NA, alpha and m-1, subset in R as:
#'
#'     logL <- RcppOUPMLLogLikelihood(tau,z,rho,mu,sigma)
#'     lnL <- logL[1]
#'     k <- logL[2]
#'     alpha <- logL[3]
#'     m1 <- logL[4]
#'
#' The return value:
#'
#'     nmstart(2,4)
#'
#'  is a matrix containing the starting theta, starting steps, length of tau
#'  and number of non-zero steps.  Each non-zero step identifies a free
#'  parameter in theta.  Subset in R as:
#'
#'     nmstart <- RcppOUPMLNMStart(tau,z,rhor,mur,sigmar,rhos,mus,sigmas)
#'     thetas <- nmstart[1,1:3]
#'     stepss <- nmstart[2,1:3]
#'     m <- nmstart[1,4]
#'     nk <- nmstart[2,4]
#'
#' The return value:
#'
#'     theta(3)
#'
#'  is a vector containing the estimated parameters, subset in R as:
#'
#'     theta <- RcppOUPMLNelderMead(tau,z,thetas,steps)
#'     rho <- theta[1]
#'     mu <- theta[2]
#'     sigma <- theta[3]
#'
#' The return value:
#'
#'     gof(2,6)
#'
#'  is a matrix containing two vectors for Invariant and Scaled Brownian Motion
#'  comparisons.  In R, the results are combined into four lists:
#'
#'     gof <- RcppOUPMLGoodnessOfFit(tau,z,lnL,alpha)
#'     theta_i <- list(rhor=gof[1,1],mu=gof[1,2],sigma=gof[1,3],lnLr=gof[1,4],k=gof[1,5],alphar=gof[1,6],m1=gof[1,7])
#'     Inv <- list(R2=gof[1,8],PVal=gof[1,9])
#'     theta_s <- list(rhor=gof[2,1],mur=gof[2,2],sigma=gof[2,3],lnLr=gof[2,4],k=gof[2,5],alphar=gof[2,6],m1=gof[2,7])
#'     SBM <- list(R2=gof[2,8],Pval=gof[2,9])
#'
#' The return value:
#'
#'     lrt(2)
#'
#'  is a vector containing R2 and Pval, subset in R as:
#'
#'     lrt <- RcppOUPMLLikelihoodRatioTest(lnL,alpha,m,lnLr)
#'     R2 <- lrt[1]
#'     PVal <- lrt[2]
#'
#' @details # Discussion
#' First, maximum likelihood estimation was implemented in R6 as a
#'  single-threaded application.  Then the R6 code was translated into
#'  Rcpp sequential code and, where possible, into RcppParallel code.  The
#'  Nelder-Mead algorithm and the Likelihood Ratio Test are hopelessly sequential.
#'  The Log Likelihood and the Goodness of Fit test are amenable to parallel
#'  processing.  Therefore, functions for maximum likelihood estimation use
#'  both sequential and parallel processing.  The R6 single-threaded code was
#'  archived.
#'
#' Below are microbenchmark median times for estimating the Ornstein-Uhlenbeck
#'  Process with 19,312 observations on an i7 CPU with 12 threads running at a
#'  maximum speed of 4.5 GHz.
#'
#'     Unit: milliseconds             R6      R6+      R6+Rcpp+
#'               function  single-thread     Rcpp  RcppParallel
#'     --------------------------------------------------------
#'               Estimate        3951.54  2386.59        144.35
#'
#' R6 single-thread takes almost 4 seconds.  R6+Rcpp, with sequential processing
#'  for both the Nelder-Mead algorithm and the Log Likelihood function, calculates
#'  1.6 times faster.  R6+Rcpp+RcppParallel, with parallel processing of the
#'  Log Likelihood function, calculates calculates 16.5 times faster than R6+Rcpp
#'  and 27.4 times faster than R6 single-thread.  Times increase linearly with
#'  sample size.  The median time for estimating with 59,256 observations is
#'  0.45198 seconds.
#'
#' RccpParallel uses Intel's Threading Building Blocks (TBB) on the CPU.  Unlike
#'  parallel processing on a GPU or accelerator, memory isn't copied and there
#'  is very little overhead.  On small problems, both the parallel and sequential
#'  code calculate within a clock tick.
#'
#' RcppParallel is an optional package.  If it is installed, it will be used.
#'  Function RcppParallelInstalled() will enquire whether code is compiled with
#'  RcppParallel or has fallen back to Rcpp.
#'
#' @details # From the Console
#' These functions are available in R, the RStudio console and RShiny apps.
#'  For example, an estimation of unrestricted parameters would be:
#'
#'     df <- OUPDataRead("OUP_Convergence")
#'     tau <- df[[1]]
#'     z <- df[[2]]
#'     nmstart <- RcppOUPMLNMStart(tau,z)
#'     thetas <- nmstart[1,1:3]
#'     steps <- nmstart[2,1:3]
#'     theta <- RcppOUPMLNelderMead(tau,z,thetas,steps)
#'
#' Good starting values are calculated from the data in RcppOUPMLNMStart(), or
#'  starting values can be chosen some other way. Both thetas and steps are called
#'  by reference and modified within RcppOUPMLNelderMead().  Calling RcppOUPMLNelderMead()
#'  again, will start from where it left off with thetas and steps.  This can
#'  be used to iterate over similar data sets without calling RcppOUPMLNMStart()
#'  each time.
#'
#' Calling functions directly from the console is slightly faster than calling
#'  them indirectly through R6 objects.  Here are microbenchmark median times for
#'  the data set with 19,312 observations:
#'
#'     Unit: milliseconds       R6+Rcpp+  Console Rcpp+
#'                function  RcppParallel   RcppParallel
#'     -----------------------------------------
#'           LogLikelihood       0.56320        0.48475
#'                 NMStart       0.40560        0.11865
#'              NelderMead     144.35000      143.42000
#'           GoodnessOfFit       1.45590        1.19890
#'     LikelihoodRatioTest       0.13540        0.00440
#'
#' The extra times taken by the R6 object are fractions of a millisecond.  For a
#'  small time penalty, the R6 object is more convenient.  All inputs are optional
#'  and are coordinated across functions.  Enter an input once and calculate several
#'  outputs.  The R6 object is reactive.  In other words, it stores the inputs and
#'  outputs and maps inputs to outputs.  If an input changes, dependent outputs are
#'  nullified and will be recalculated, as requested, but nothing is calculated twice.
#'  The console stores outputs in the global environment, but there is no map to
#'  inputs and outputs can be stale.  Another advantage of the R6 object is predefined
#'  plots with Plotly. The same simulation can plotted different ways without
#'  recalculation.
#'
#' The overhead of setting up RcppParallel means that small problems will
#'  calculate more slowly.  But small problems calculate in microseconds, anyway.
#'
#' Sequential calculations are reproducible, but parallel calculations are not.
#'  Two runs of the same problem will agree to about 12 significant digits, but
#'  disagree thereafter.  For exact arithmetic, order doesn't matter.  For
#'  floating-point arithmetic, it does.  For example, a Log Likelihood is rounded
#'  to 15 digits as Log Likelihoods for each observation are added.  Changing the
#'  order changes the rounding and may give slightly different answers.  The TBB
#'  scheduler determines the order.
#'
#' Potentially, the functions could be imported into other packages.
#'
#' @name MaximumLikelihood_Rcpp
NULL

#' @rdname MaximumLikelihood_Rcpp
#' @usage  RcppOUPMLLogLikelihood(tau,z,rho,mu,sigma)
#' @param  tau   vector of times
#' @param  z     vector of states
#' @param  rho   rate parameter 0<=rho<inf
#' @param  mu    location parameter -inf<mu<inf
#' @param  sigma scale parameter -inf<sigma<inf
#' @return logL(4) <- RcppOUPMLLogLikelihood()
#' @export
RcppOUPMLLogLikelihood <- function(tau, z, rho, mu, sigma) {
    .Call(`_GregsOUPR6_RcppOUPMLLogLikelihood`, tau, z, rho, mu, sigma)
}

#' @rdname MaximumLikelihood_Rcpp
#' @usage  RcppOUPMLNMStart(tau,z,rhor,mur,sigmar,rhos,mus,sigmas)
#' @param  tau    vector of times
#' @param  z      vector of states
#' @param  rhor   optional constant to fix the rate parameter 0<=rhor<inf
#' @param  mur    optional constant to fix the location parameter -inf<mur<inf
#' @param  sigmar optional constant to fix scale parameter -inf<sigmar<inf
#' @param  rhos   optional starting value for the rate parameter 0<=rhos<inf
#' @param  mus    optional starting value for the location parameter -inf<mus<inf
#' @param  sigmas optional starting value the scale parameter -inf<sigmas<inf
#' @return start(2,4) <- RcppOUPMLNMStart()
#' @export
RcppOUPMLNMStart <- function(tau, z, rhor = NULL, mur = NULL, sigmar = NULL, rhos = NULL, mus = NULL, sigmas = NULL) {
    .Call(`_GregsOUPR6_RcppOUPMLNMStart`, tau, z, rhor, mur, sigmar, rhos, mus, sigmas)
}

#' @rdname MaximumLikelihood_Rcpp
#' @usage  RcppOUPMLNelderMead(tau,z,theta,steps)
#' @param  tau   vector of times
#' @param  z     vector of states
#' @param  theta vector containing rho, mu and sigma
#' @param  steps vector of 0's or 1's, 0 for fixed, 1 for variable
#' @return theta(3) <- RcppOUPMLNelderMead()
#' @export
RcppOUPMLNelderMead <- function(tau, z, theta, steps) {
    .Call(`_GregsOUPR6_RcppOUPMLNelderMead`, tau, z, theta, steps)
}

#' @rdname MaximumLikelihood_Rcpp
#' @usage  RcppOUPMLGoodnessOfFit(tau,z,lnL,alpha)
#' @param  tau   vector of times
#' @param  z     vector of states
#' @param  lnL   log likelihood of estimates lnL<0
#' @param  alpha identifies the distribution of lnL 0.5<alpha<1
#' @return gof(2,6) <- RcppOUPMLGoodnessOfFit()
#' @export
RcppOUPMLGoodnessOfFit <- function(tau, z, lnL, alpha) {
    .Call(`_GregsOUPR6_RcppOUPMLGoodnessOfFit`, tau, z, lnL, alpha)
}

#' @rdname MaximumLikelihood_Rcpp
#' @usage  RcppOUPMLLikelihoodRatioTest(lnL,alpha,m,lnLr)
#' @param  lnL   log likelihood of estimates lnL<0
#' @param  alpha identifies the distribution of lnL 0.5<alpha<1
#' @param  m     number of times t in the data set
#' @param  lnLr  the log likelihood for restricted parameters lnLr<=lnL
#' @return lrt(2) <- RcppOUPMLLikelihoodRatioTest()
#' @export
RcppOUPMLLikelihoodRatioTest <- function(lnL, alpha, m, lnLr) {
    .Call(`_GregsOUPR6_RcppOUPMLLikelihoodRatioTest`, lnL, alpha, m, lnLr)
}

#' @title MonteCarlo_Rcpp functions for simulating an Ornstein-Uhlenbeck Process
#'
#' @description
#' Calculations for the R6 class 'MonteCarlo', with parallel processing.
#'
#' @details # Notes on Values
#' Return values are vectors and matrices allocated in Rcpp.  The dimensions are
#'  shown for information.  Of course, do not include them in R calls.  For example:
#'
#'     stdnorm <- RcppOUPMCStandardNormal(m,skip,paths,seed)
#'
#' The return values:
#'
#'     stdnorm((m-1)*skip,paths)
#'     forward(m,paths)
#'     backward(m,paths)
#'     heat(m,n)
#'
#'  are matrices of pseudo-random standard normal variables, forward paths,
#'  backward paths and heat maps.
#'
#' The return value:
#'
#'     minmax(2)
#'
#'  is a vector of minimum and maximum values, subset in R as:
#'
#'     minmax <- RcppOUPMCMinMax(matPaths)
#'     min <- minmax[1]
#'     max <- minmax[2]
#'
#' The return value:
#'
#'     bndfpt(m+1,paths)
#'
#'  is a matrix of bounded paths with a vector of first passage times for each
#'  path in row m+1.  There are NA entries for paths which previously hit the
#'  threshold and NA entries in row m+1 for paths which have yet to hit the
#'  threshold.  Subset in R as:
#'
#'     bndfpt <- RcppOUPMCBoundedPathIntegralEquation(stdnorm,k,x,m,skip,dt,rho,mu,sigma)
#'     bounded <- bndfpt[1:m,,drop=FALSE]
#'     fpt <- bndfpt[m+1,,drop=FALSE]
#'
#' The return value:
#'
#'     mvdpd(m,3*n+2)
#'
#'  is a composite matrix containing two vectors for means and variances and three
#'  matrices for densities, probabilities and double integrals.  The vectors and
#'  matrices are subset in R as:
#'
#'     mvdpd <- RcppOUPMCForwardCountY(forward,y,psi)
#'     means <- mvdpd[,1,drop=FALSE]
#'     variances <- mvdpd[,2,drop=FALSE]
#'     densities <- mvdpd[,3:(n+2),drop=FALSE]
#'     probabilities <- mvdpd[,(n+3):(2*n+2),drop=FALSE]
#'     doubleintegrals <- mvdpd[,(2*n+3):(3*n+2),drop=FALSE]
#'
#' Similarly, the return value:
#'
#'     dpo(m,3*n)
#'
#'  is a composite of three contiguous matrices for prior densities, prior
#'  probabilities and options, subset in R as:
#'
#'     dpo <- RcppOUPMCBackwardCountX(backward,x,phi,rho,r,ds)
#'     densities <- dpo[,1:n,drop=FALSE]
#'     probabilities <- dpo[,(n+1):(2*n),drop=FALSE]
#'     options <- dpo[,(2*n+1):(3*n),drop=FALSE]
#'
#' The return values:
#'
#'     pctdp(m,5)
#'
#'  are matrices of five columns.  The first column has only five entries for
#'  times at the mode, median, mean, lower percentile, and upper percentile. The
#'  second and third columns each have five entries containing the corresponding
#'  densities and probabilities.  The fourth and fifth columns contain contain m
#'  entries for either visiting time or first passage time densities and
#'  probabilities.  The columns are subset in R as:
#'
#'     pctdp <- RcppOUPMCForwardCountT(forward,k,dt,rho,mu,sigma,Ppct)
#'     mode <- pctdp[1,1:3,drop=FALSE]
#'     median <- pctdp[2,1:3,drop=FALSE]
#'     mean <- pctdp[3,1:3,drop=FALSE]
#'     lowerpct <- pctdp[4,1:3,drop=FALSE]
#'     upperpct <- pctdp[5,1:3,drop=FALSE]
#'     densities <- pctdp[,4,drop=FALSE]
#'     probabilities <- pctdp[,5,drop=FALSE]
#'
#' @details # Discussion
#' A single-threaded R6 object is fast enough for many calculations, but not
#'  for Monte-Carlo simulations.  Attempts at parallel processing using parApply()
#'  and future_apply() failed.  The whole R6 object is copied to each thread,
#'  which locks up the computer.  Rccp is often hundreds of times faster and makes
#'  Monte-Carlo simulations practical for interactive applications such as RStudio
#'  and RShiny. RcppParallel speeds the calculations another five to eight times.
#'
#' For the simulations, both a 4th order Runge-Kutta method and the stochastic
#'  integral equation are implemented.  With argument skip set to 10, and the
#'  same seed in the random number generators, they give the same paths to about six
#'  significant digits, but the stochastic integral equation calculates faster.
#'
#' A typical simulation might require 100,000,000 standard normal variables.  On
#'  an i7 processor with 12 threads running at a maximum speed of 4.5 GHz,
#'  microbenchmark median times to generate the standard normal variables are:
#'
#'     Unit: milliseconds             R6       R6+           R6+
#'               function  single-thread      Rcpp  RcppParallel
#'     ---------------------------------------------------------
#'         StandardNormal       5779.756  4002.566       660.010
#'
#' R6 single-thread and R6+Rcpp use rnorm(), the standard random number
#'  generator in R.  The R6+RcppParallel uses sitmo::prng_engine with a Box-Muller
#'  transform for uniform to normal random variables.  R6+Rcpp is 1.4 times
#'  faster than R6 single-thread.  R6+RcppParallel is 6.1 times faster than
#'  R6+Rcpp and 8.8 times faster than R6 single-thread.
#'
#' Once the standard normal variables are calculated, microbenchmark median
#'  times to simulate the 4th order Runge-Kutta and stochastic integral
#'  equation for 100,000 paths over 100 time intervals with skip=10 are:
#'
#'     Unit: milliseconds                      R6       R6+           R6+
#'                        function  single-thread      Rcpp  RcppParallel
#'     ------------------------------------------------------------------
#'           ForwardPathRungeKutta      207798.80  2688.932       242.135
#'     ForwardPathIntegralEquation       51298.03   416.793        47.316
#'
#' The stochastic integral equation calculates from 4.1 to 6.5 times faster than
#'  the 4th order Runge-Kutta method.  R6+Rcpp calculates from 77.3 to 123.1 times
#'  faster than R6 single-thread.  R6+RcppParallel calculates from 8.8 to 11.1
#'  times faster than R6+Rcpp and from 858.2 to 1084.2 times faster than R6
#'  single-thread.
#'
#' The skip parameter can increase the accuracy of the Runge-Kutta method and
#'  enable a better count of First Passage Times.  The stochastic integral
#'  equation is not improved by skip=10 and is penalized in the timings above.
#'
#' Forward, backward and bounded paths can be binned and counted to approximate
#'  solutions. The approximations converge to analytical solutions as the number
#'  of paths increases.  Binning and counting 1,000,000 paths will be accurate to
#'  3 or 4 significant digits.  Here are microbenchmark median times for the
#'  stochastic integral equation over 100,000 and 1,000,000 paths for 100 time
#'  intervals with skip=1, as calculated by R6+RccpParallel:
#'
#'     Unit: milliseconds              paths                paths
#'                        function   100,000            1,000,000
#'     ----------------------------------------------------------
#'                  StandardNormal   57.2060             588.7932
#'     ForwardPathIntegralEquation   18.9317  ________   187.9792  _________
#'                        subtotal             76.1377              776.7524
#'                   ForwardCountY   70.0579  ________   906.2226  _________
#'                           total            146.1956             1682.9750
#'
#' Times go up approximately linearly with the number of paths.  Looking at the
#'  subtotals for simulating from a standing start, 100,000 paths will take
#'  0.076 seconds and 1,000,000 paths will take 0.777 seconds.  Looking at the
#'  totals for counting from a standing start, 100,000 paths will take 0.146
#'  seconds and 1,000,000 paths will take 1.683 seconds.  About a third of that
#'  time is spent generating the standard normal variables, which can be reused.
#'  Subsequent simulations will only take 0.019 and 0.188 seconds.  Forward Paths
#'  are not reused and subsequent simulations plus counting will take 0.089 and
#'  1.094 seconds.
#'
#' The function ForwardCountY bins and counts means, variances, transition densities,
#'  transition probabilities and double integrals.  So five sets of plots can be
#'  drawn from one set of calculations. For comparison, a 3D plot by Plotly will
#'  take up to a second on an RTX 2070 GPU.  So calculations are only a part of
#'  the job.
#'
#' Rcpp versions of the functions were coded first.  All but one function were
#'  translated into RcppParallel versions.  RccpParallel uses Intel's Threading
#'  Building Blocks (TBB) on the CPU.  Unlike parallel processing on a GPU or
#'  accelerator, memory isn't copied and there is less overhead.  On trivially
#'  small problems, sequential versions calculate faster.  On large problems,
#'  parallel versions calculate much faster.
#'
#' RcppParallel and sitmo are optional packages.  If installed, they will be
#'  used.  Function RcppParallelInstalled() will enquire whether calculations
#'  will use RcppParallel or fall back to Rcpp only.  Function RcppsitmoInstalled()
#'  will enquire whether random numbers will be generated by RcppPrallel with
#'  sitmo() or fall back to Rcpp with rnorm().
#'
#' @details # From the Console
#' These functions are available in R, the RStudio console and RShiny apps.
#'  For example, a simulation of 1,000,000 forward paths over 100 time intervals
#'  with skip=1 would be:
#'
#'      stdnorm <- RcppOUPMCStandardNormal(101,1,1000000,9999)
#'      fwd <- RcppOUPMCForwardPathIntegralEquation(stdnorm,15,100,1,0.1,0.5,-15,15)
#'
#' A microbenchmark comparison of indirectly calling the RcppParallel functions
#'  from R6 with directly calling them from the console is:
#'
#'     Unit: milliseconds                     R6+        Console
#'                         function   RcppParallel  RcppParallel
#'     -------------------------------------------------------------------
#'      ForwardPathIntegralEquation       807.2069      837.4392
#'     BackwardPathIntegralEquation       807.4201      837.8897
#'      BoundedPathIntegralEquation      1200.3780      834.9122
#'
#' These timings are from a standing start, generating the random variables before
#'  simulating the paths.  For Forward and Backward Paths, the R6 object is faster,
#'  but for Bounded Paths, it is much slower.  Bounded Paths hit the boundary and have
#'  NA values thereafter.  We might speculate that R6 is slow with NA values.
#'
#' The R6 object has advantages over the console.  All inputs are optional and are
#'  coordinated across functions.  Enter an input once and calculate several outputs.
#'  The R6 object is reactive.  In other words, it stores the inputs and outputs and
#'  maps inputs to outputs.  If an input changes, dependent outputs are nullified and
#'  will be recalculated, as requested, but nothing is calculated twice.  The console
#'  stores outputs in the global environment, but there is no map to inputs and they
#'  can be stale.  Another advantage of the  R6 object is predefined plots with Plotly.
#'  The same simulation can plotted different ways without recalculation.
#'
#' The parallel code has more overhead and is slower on small problems. Here
#'  are microbenchmark median times for simulating a small number of Forward Paths
#'  by calling the Rcpp and RcppParallel functions from the console:
#'
#'     Unit: milliseconds  Console       Console
#'                  paths     Rcpp   RcppParallel
#'     ------------------------------------------
#'                    100  0.06970        0.07600
#'                  1,000  0.55425        0.23540
#'
#' For 100 paths, the Rcpp sequential function takes less time, but for 1,000 paths
#'  it takes over twice as long.  Most simulations will have more than 1,000 paths.
#'  So users get no choice.  By default, RcppParallel functions are compiled if
#'  RcppParallel is installed. Otherwise compilation falls back to Rcpp.
#'
#' Potentially, the functions could be imported into other packages.
#'
#' @name MonteCarlo_Rcpp
NULL

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCMinMax(matPaths)
#' @param  matPaths matrix of paths
#' @return minmax(2) <- RcppOUPMCMinMax()
#' @export
RcppOUPMCMinMax <- function(matPaths) {
    .Call(`_GregsOUPR6_RcppOUPMCMinMax`, matPaths)
}

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCStandardNormal(m,skip,paths,seed)
#' @param  m    number of rows for states over time
#' @param  skip subdivide time interval but report every ds or dt 0<skip<20
#' @param  paths number of columns for paths
#' @param  seed seed for reproducibility
#' @return stdnorm((m-1)*skip,paths) <- RcppOUPMCStandardNormal()
#' @export
RcppOUPMCStandardNormal <- function(m, skip, paths, seed) {
    .Call(`_GregsOUPR6_RcppOUPMCStandardNormal`, m, skip, paths, seed)
}

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCForwardPathRungeKutta(stdnorm,x,m,skip,dt,rho,mu,sigma)
#' @param  stdnorm matrix of standard normal shocks
#' @param  x       initial state or vector of backward states
#' @param  m       number of rows for states over time
#' @param  skip    subdivide time interval but report every ds or dt 0<skip<50
#' @param  dt      time interval for initial value problems
#' @param  rho     rate parameter 0<=rho<inf
#' @param  mu      location parameter -inf<mu<inf
#' @param  sigma   scale parameter -inf<sigma<inf
#' @return forward(m,paths) <- RcppOUPMCForwardPathRungeKutta()
#' @export
RcppOUPMCForwardPathRungeKutta <- function(stdnorm, x, m, skip, dt, rho, mu, sigma) {
    .Call(`_GregsOUPR6_RcppOUPMCForwardPathRungeKutta`, stdnorm, x, m, skip, dt, rho, mu, sigma)
}

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCBackwardPathRungeKutta(stdnorm,y,m,skip,ds,rho,mu,sigma)
#' @param  stdnorm matrix of standard normal shocks
#' @param  y       terminal state or vector of forward states
#' @param  m       number of rows for states over time
#' @param  skip    subdivide time interval but report every ds or dt 0<skip<50
#' @param  ds      time interval for terminal value problems
#' @param  rho     rate parameter 0<=rho<inf
#' @param  mu      location parameter -inf<mu<inf
#' @param  sigma   scale parameter -inf<sigma<inf
#' @return backward(m,paths) <- RcppOUPMCBackwardPathRungeKutta()
#' @export
RcppOUPMCBackwardPathRungeKutta <- function(stdnorm, y, m, skip, ds, rho, mu, sigma) {
    .Call(`_GregsOUPR6_RcppOUPMCBackwardPathRungeKutta`, stdnorm, y, m, skip, ds, rho, mu, sigma)
}

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCBoundedPathRungeKutta(stdnorm,k,x,m,skip,dt,rho,mu,sigma)
#' @param  stdnorm matrix of standard normal shocks
#' @param  k       threshold -inf<k<inf
#' @param  x       initial state or vector of backward states
#' @param  m       number of rows for states over time
#' @param  skip    subdivide time interval but report every ds or dt 0<skip<20
#' @param  dt      time interval for initial value problems
#' @param  rho     rate parameter 0<=rho<inf
#' @param  mu      location parameter -inf<mu<inf
#' @param  sigma   scale parameter -inf<sigma<inf
#' @return bndfpt(m+1,paths) <- RcppOUPMCBoundedPathRungeKutta()
#' @export
RcppOUPMCBoundedPathRungeKutta <- function(stdnorm, k, x, m, skip, dt, rho, mu, sigma) {
    .Call(`_GregsOUPR6_RcppOUPMCBoundedPathRungeKutta`, stdnorm, k, x, m, skip, dt, rho, mu, sigma)
}

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCForwardPathIntegralEquation(stdnorm,x,m,skip,dt,rho,mu,sigma)
#' @param  stdnorm matrix of standard normal shocks
#' @param  x       initial state or vector of backward states
#' @param  m       number of rows for states over time
#' @param  skip    subdivide time interval but report every ds or dt 0<skip<20
#' @param  dt      time interval for initial value problems
#' @param  rho     rate parameter 0<=rho<inf
#' @param  mu      location parameter -inf<mu<inf
#' @param  sigma   scale parameter -inf<sigma<inf
#' @return forward(m,paths) <- RcppOUPMCForwardPathIntegralEquation()
#' @export
RcppOUPMCForwardPathIntegralEquation <- function(stdnorm, x, m, skip, dt, rho, mu, sigma) {
    .Call(`_GregsOUPR6_RcppOUPMCForwardPathIntegralEquation`, stdnorm, x, m, skip, dt, rho, mu, sigma)
}

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCBackwardPathIntegralEquation(stdnorm,y,m,skip,ds,rho,mu,sigma)
#' @param  stdnorm matrix of standard normal shocks
#' @param  y       terminal state or vector of forward states
#' @param  m       number of rows for states over time
#' @param  skip    subdivide time interval but report every ds or dt 0<skip<20
#' @param  ds      time interval for terminal value problems
#' @param  rho     rate parameter 0<=rho<inf
#' @param  mu      location parameter -inf<mu<inf
#' @param  sigma   scale parameter -inf<sigma<inf
#' @return backward(m,paths) <- RcppOUPMCBackwardPathIntegralEquation()
#' @export
RcppOUPMCBackwardPathIntegralEquation <- function(stdnorm, y, m, skip, ds, rho, mu, sigma) {
    .Call(`_GregsOUPR6_RcppOUPMCBackwardPathIntegralEquation`, stdnorm, y, m, skip, ds, rho, mu, sigma)
}

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCBoundedPathIntegralEquation(stdnorm,k,x,m,skip,dt,rho,mu,sigma)
#' @param  stdnorm matrix of standard normal shocks
#' @param  x       initial state or vector of backward states
#' @param  k       threshold -inf<k<inf
#' @param  m       number of rows for states over time
#' @param  skip    subdivide time interval but report every ds or dt 0<skip<20
#' @param  dt      time interval for initial value problems
#' @param  rho     rate parameter 0<=rho<inf
#' @param  mu      location parameter -inf<mu<inf
#' @param  sigma   scale parameter -inf<sigma<inf
#' @return bndfpt(m+1,paths) <- RcppOUPMCBoundedPathIntegralEquation()
#' @export
RcppOUPMCBoundedPathIntegralEquation <- function(stdnorm, k, x, m, skip, dt, rho, mu, sigma) {
    .Call(`_GregsOUPR6_RcppOUPMCBoundedPathIntegralEquation`, stdnorm, k, x, m, skip, dt, rho, mu, sigma)
}

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCForwardCountY(forward,y,psi)
#' @param  forward matrix of forward paths
#' @param  y       terminal state or vector of forward states
#' @param  psi     <=0 for integral -inf to y, >0 for integral y to inf
#' @return mvdpd(m,3*n+2) <- RcppOUPMCForwardCountY()
#' @export
RcppOUPMCForwardCountY <- function(forward, y, psi) {
    .Call(`_GregsOUPR6_RcppOUPMCForwardCountY`, forward, y, psi)
}

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCBackwardCountX(backward,x,phi,rho,r,ds)
#' @param  backward matrix of backward paths
#' @param  x       initial state or vector of backward states
#' @param  phi     <=0 for integral -inf to x, >0 for integral x to inf
#' @param  rho      rate parameter 0<=rho<inf
#' @param  r        discount rate 0<r
#' @param  ds       time interval for terminal value problems
#' @return dpo(m,3*n) <- RcppOUPMCBackwardCountX()
#' @export
RcppOUPMCBackwardCountX <- function(backward, x, phi, rho, r, ds) {
    .Call(`_GregsOUPR6_RcppOUPMCBackwardCountX`, backward, x, phi, rho, r, ds)
}

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCForwardCountT(forward,k,dt,rho,mu,sigma,Ppct)
#' @param  forward matrix of forward paths
#' @param  k       threshold -inf<k<inf
#' @param  dt      time interval for initial value problems
#' @param  rho     rate parameter 0<=rho<inf
#' @param  mu      location parameter -inf<mu<inf
#' @param  sigma   scale parameter -inf<sigma<inf
#' @param  Ppct    probability for a percentile 0.01<pct<0.99
#' @return pctdp(m,5) <- RcppOUPMCForwardCountT()
#' @export
RcppOUPMCForwardCountT <- function(forward, k, dt, rho, mu, sigma, Ppct) {
    .Call(`_GregsOUPR6_RcppOUPMCForwardCountT`, forward, k, dt, rho, mu, sigma, Ppct)
}

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCBoundedCountT(fpt,m,dt,Ppct)
#' @param  fpt     vector of first passage times
#' @param  m       number of rows for states over time
#' @param  dt      time interval for initial value problems
#' @param  Ppct    probability for a percentile 0.01<pct<0.99
#' @return pctdp(m,5) <- RcppOUPMCBoundedCountT()
#' @export
RcppOUPMCBoundedCountT <- function(fpt, m, dt, Ppct) {
    .Call(`_GregsOUPR6_RcppOUPMCBoundedCountT`, fpt, m, dt, Ppct)
}

#' @rdname MonteCarlo_Rcpp
#' @usage  RcppOUPMCHeatCountZ(matPaths,z)
#' @param  matPaths matrix of paths
#' @param  z        vector of states
#' @return heat(m,n) <- RcppOUPMCHeatCountZ()
#' @export
RcppOUPMCHeatCountZ <- function(matPaths, z) {
    .Call(`_GregsOUPR6_RcppOUPMCHeatCountZ`, matPaths, z)
}

#' @title Optional packages for parallel processing
#'
#' @description
#' Queries whether functions are compiled with RcppParallel or fall back
#'  to Rcpp only.  Also queries whether random numbers are generated
#'  by RcppParallel using sitmo() or fall back to Rcpp using rnorm().
#'
#' @details # Discussion
#' Rcpp calculates hundreds of times faster than R6 objects.  RcppParallel
#'  calculates five to eight times faster than Rcpp on a typical laptop with
#'  12 threads, and thousands of times faster than R6 objects.  For Monte Carlo
#'  simulations, RcppParallel using sitmo() generates random numbers six times
#'  faster Rcpp using rnorm() and nine times faster R6 using rnorm().  Both
#'  RcppParallel and sitmo are optional but recommended:
#'
#'      install.packages("RcppParallel", "sitmo")
#'
#' @name OptionalPackages
NULL

#' @rdname OptionalPackages
#' @usage  RcppParallelInstalled()
#' @return bool <- RcppParallelInstalled()
#' @export
RcppParallelInstalled <- function() {
    .Call(`_GregsOUPR6_RcppParallelInstalled`)
}

#' @rdname OptionalPackages
#' @usage RcppsitmoInstalled()
#' @return bool <- RcppsitmoInstalled()
#' @export
RcppsitmoInstalled <- function() {
    .Call(`_GregsOUPR6_RcppsitmoInstalled`)
}

